// core/interfaces.ts
// Canton/Daml Finance Interfaces - Project Independent
// DO NOT EDIT - Generated by generate-canton-api.ts

import type { Party, Optional, Numeric, Set } from './primitives';

// ═══════════════════════════════════════════════════════════════
// IDENTIFIERS
// ═══════════════════════════════════════════════════════════════

/**
 * Generic identifier wrapper.
 * Wraps a string ID for type safety.
 */
export interface Id {
  unpack: string;
}

/**
 * Unique identifier for an account.
 * Combines custodian, owner, and account ID.
 */
export interface AccountKey {
  /** Party responsible for custody */
  custodian: Party;
  /** Beneficial owner of the account */
  owner: Party;
  /** Unique ID within custodian namespace */
  id: Id;
}

/**
 * Unique identifier for a financial instrument.
 * Instruments are versioned to support lifecycle events.
 */
export interface InstrumentKey {
  /** Party responsible for safekeeping */
  depository: Party;
  /** Party that issued the instrument */
  issuer: Party;
  /** Unique identifier (e.g., 'USD', 'AAPL') */
  id: Id;
  /** Version for lifecycle changes */
  version: string;
  /** Supported holding behaviors */
  holdingStandard: HoldingStandard;
}

/**
 * Unique identifier for a holding factory.
 */
export interface HoldingFactoryKey {
  provider: Party;
  id: Id;
}

/**
 * Unique identifier for a settlement instruction.
 */
export interface InstructionKey {
  instructor: Party;
  batchId: Id;
  id: Id;
}

// ═══════════════════════════════════════════════════════════════
// FINANCIAL TYPES
// ═══════════════════════════════════════════════════════════════

/**
 * Generic quantity with unit and amount.
 * The unit is typically an InstrumentKey for financial quantities.
 * @example { unit: usdInstrument, amount: "1000.00" }
 */
export interface Quantity<U = InstrumentKey, A = Numeric> {
  unit: U;
  amount: A;
}

/**
 * Account controller configuration.
 * Defines which parties can authorize debits and credits.
 */
export interface Controllers {
  /** Parties that can authorize outgoing transfers (debits) */
  outgoing: Set<Party>;
  /** Parties that can authorize incoming transfers (credits) */
  incoming: Set<Party>;
}

/**
 * Lock on a contract preventing certain operations.
 * Used during settlement for atomicity guarantees.
 */
export interface Lock {
  /** Parties holding the lock */
  lockers: Set<Party>;
  /** Context identifiers for the lock */
  context: Set<string>;
  /** Type of lock behavior */
  lockType: LockType;
}

/**
 * Settlement step with routing information.
 * Specifies sender, receiver, custodian, and quantity.
 */
export interface RoutedStep {
  sender: Party;
  receiver: Party;
  custodian: Party;
  quantity: Quantity;
}

/**
 * Settlement step without routing (custodian TBD).
 */
export interface Step {
  sender: Party;
  receiver: Party;
  quantity: Quantity;
}

/**
 * Custodian hierarchy for settlement routing.
 */
export interface Hierarchy {
  rootCustodian: Party;
  pathsToRootCustodian: Party[][];
}

// ═══════════════════════════════════════════════════════════════
// DATE/TIME TYPES
// ═══════════════════════════════════════════════════════════════

/**
 * Business day adjustment for date calculations.
 */
export interface BusinessDayAdjustment {
  calendarIds: string[];
  convention: BusinessDayConventionEnum;
}

/**
 * Holiday calendar definition.
 */
export interface HolidayCalendarData {
  id: string;
  weekend: DayOfWeek[];
  holidays: string[];
}

/**
 * Date offset for schedule calculations.
 */
export interface DateOffset {
  period: PeriodEnum;
  periodMultiplier: number;
  dayType: Optional<DayTypeEnum>;
  businessDayConvention: BusinessDayConventionEnum;
  businessCenters: string[];
}

/**
 * Time period definition.
 */
export interface Period {
  period: PeriodEnum;
  periodMultiplier: number;
}

/**
 * Schedule frequency with roll convention.
 */
export interface Frequency {
  period: Period;
  rollConvention: RollConventionEnum;
}

/**
 * Single period in a schedule.
 */
export interface SchedulePeriod {
  adjustedEndDate: string;
  adjustedStartDate: string;
  unadjustedEndDate: string;
  unadjustedStartDate: string;
  stubType: Optional<StubPeriodTypeEnum>;
}

/**
 * Periodic schedule definition.
 */
export interface PeriodicSchedule {
  effectiveDate: string;
  terminationDate: string;
  firstRegularPeriodStartDate: Optional<string>;
  lastRegularPeriodEndDate: Optional<string>;
  frequency: Frequency;
  businessDayAdjustment: BusinessDayAdjustment;
  effectiveDateBusinessDayAdjustment: Optional<BusinessDayAdjustment>;
  terminationDateBusinessDayAdjustment: Optional<BusinessDayAdjustment>;
  stubPeriodType: Optional<StubPeriodTypeEnum>;
}

// ═══════════════════════════════════════════════════════════════
// ENUMS (Opaque types - actual values depend on Daml model)
// ═══════════════════════════════════════════════════════════════

export type HoldingStandard = string;
export type LockType = { tag: string; value?: unknown };
export type Allocation = { tag: string; value?: unknown };
export type Approval = { tag: string; value?: unknown };
export type BusinessDayConventionEnum = { tag: string };
export type DayOfWeek = { tag: string };
export type PeriodEnum = { tag: string };
export type DayTypeEnum = { tag: string };
export type StubPeriodTypeEnum = { tag: string };
export type RollConventionEnum = { tag: string };
