// core/primitives.ts
// Canton/Daml Primitives - Project Independent
// DO NOT EDIT - Generated by generate-canton-api.ts

/**
 * Unique identifier for a party on the Canton ledger.
 * Parties represent participants (users, institutions, services) in the network.
 * @example "Alice::1220abc123"
 */
export type Party = string;

/**
 * Type-safe contract identifier.
 * The generic parameter ensures compile-time type checking when exercising choices.
 * @example const accountCid: ContractId<Account> = "00abc123" as ContractId<Account>;
 */
export type ContractId<T> = string & { readonly __contractType: T };

/**
 * Optional value wrapper - value may be null.
 */
export type Optional<T> = T | null;

/**
 * ISO 8601 timestamp string.
 * @example "2024-01-15T10:30:00Z"
 */
export type Time = string;

/**
 * ISO 8601 date string (YYYY-MM-DD).
 * @example "2024-01-15"
 */
export type Date = string;

/**
 * Decimal number as string to preserve arbitrary precision.
 * Use for financial amounts to avoid floating point errors.
 * @example "1000.50"
 */
export type Numeric = string;

/**
 * Integer number represented as string.
 * Daml JSON encodes Int values as strings to preserve precision.
 */
export type Int = string;

/**
 * Text string.
 */
export type Text = string;

/**
 * Boolean value.
 */
export type Bool = boolean;

/**
 * Unit type - represents "no value".
 */
export type Unit = Record<string, never>;

/**
 * String-keyed map/dictionary.
 */
export type TextMap<V> = Record<string, V>;

/**
 * Generic Daml Map<K, V> representation.
 * Daml JSON API encodes Map as an array of key/value pairs.
 */
export type DamlMap<K, V> = Array<[K, V]>;

/**
 * Set represented as array (Daml sets serialize as arrays).
 */
export type Set<T> = T[];

/**
 * Contract wrapper with ID and payload.
 */
export interface Contract<T> {
  contractId: ContractId<T>;
  payload: T;
  createdAt?: Time;
}

/**
 * Query result page for paginated queries.
 */
export interface Page<T> {
  contracts: Contract<T>[];
  offset?: string;
}

/**
 * Command to be submitted to the ledger.
 * Wraps the command type for type-safe submission.
 */
export interface Command<T> {
  templateId: string;
  choice?: string;
  contractId?: string;
  argument: unknown;
  _resultType?: T;
}

/**
 * Result of exercising a choice.
 */
export interface ExerciseResult<T> {
  exerciseResult: T;
  events: unknown[];
}

/**
 * Ledger connection interface for type-safe ledger operations.
 */
export interface LedgerConnection {
  query<T>(templateId: string, filter?: Partial<T>): Promise<Contract<T>[]>;
  create<T>(templateId: string, payload: T): Promise<ContractId<T>>;
  exercise<T, R>(templateId: string, contractId: ContractId<T>, choice: string, args: unknown): Promise<ExerciseResult<R>>;
  fetch<T>(contractId: ContractId<T>): Promise<Contract<T> | null>;
}
