// react/context/LedgerContext.tsx
// Ledger React context provider
// DO NOT EDIT - Generated by generate-canton-react.ts

import * as React from 'react';
import { createContext, useMemo } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import type { Party, LedgerConnection } from '../../core';
import { CantonLedgerClient } from '../../ledger';

export interface LedgerContextValue {
  ledger: LedgerConnection;
  party: Party;
}

export const LedgerContext = createContext<LedgerContextValue | null>(null);

export interface CantonProviderProps {
  config: {
    ledgerUrl: string;
    token?: string;
  };
  party: Party;
  children: React.ReactNode;
  queryClient?: QueryClient;
}

export function CantonProvider({
  config,
  party,
  children,
  queryClient: providedClient,
}: CantonProviderProps): React.ReactElement {
  const ledger = useMemo(
    () => new CantonLedgerClient(party, config.ledgerUrl, config.token),
    [party, config.ledgerUrl, config.token]
  );

  const queryClient = useMemo(
    () =>
      providedClient ??
      new QueryClient({
        defaultOptions: {
          queries: {
            staleTime: 5000,
            retry: 2,
          },
        },
      }),
    [providedClient]
  );

  const contextValue = useMemo(() => ({ ledger, party }), [ledger, party]);

  return (
    <QueryClientProvider client={queryClient}>
      <LedgerContext.Provider value={contextValue}>{children}</LedgerContext.Provider>
    </QueryClientProvider>
  );
}
