// react/context/useLedger.ts
// Hook to access ledger context
// DO NOT EDIT - Generated by generate-canton-react.ts

import { useContext } from 'react';
import { LedgerContext, LedgerContextValue } from './LedgerContext';

export function useLedger(): LedgerContextValue {
  const context = useContext(LedgerContext);
  if (!context) {
    throw new Error('useLedger must be used within a CantonProvider');
  }
  return context;
}
