// ledger/client.ts
// Canton JSON API Client
// DO NOT EDIT - Generated by generate-canton-api.ts

import type { LedgerConfig } from "./config";
import { createConfig, defaultConfig, createJwtToken } from "./config";
import { PackageResolver, getPackageResolver } from "./resolver";
import type {
  LedgerConnection,
  Contract,
  ContractId,
  ExerciseResult,
  Party,
} from "../core/primitives";
import {
  ConnectionError,
  TimeoutError,
  UnauthorizedError,
  LedgerError,
  LedgerErrorCode,
} from "./errors";

// ═══════════════════════════════════════════════════════════════
// CANTON LEDGER CLIENT
// ═══════════════════════════════════════════════════════════════

/**
 * Canton JSON API client implementing LedgerConnection interface.
 * Uses the standard Canton JSON API endpoints.
 *
 * Features:
 * - Automatic JWT token generation for Canton sandbox
 * - Runtime package hash resolution for template IDs
 * - Type-safe contract operations
 *
 * @example
 * ```ts
 * import { CantonLedgerClient } from './ledger';
 *
 * // With explicit URL (auto-generates JWT, auto-resolves package hashes)
 * const ledger = new CantonLedgerClient('alice::1220...', 'http://localhost:7575');
 *
 * // With config object
 * const ledger = new CantonLedgerClient('alice::1220...', { host: 'localhost', port: 7575 });
 *
 * // With custom token
 * const ledger = new CantonLedgerClient('alice::1220...', { token: mySignedJwt });
 * ```
 */
export class CantonLedgerClient implements LedgerConnection {
  private baseUrl: string;
  private headers: Record<string, string>;
  private party: Party;
  private timeout: number;
  private resolver: PackageResolver;

  /**
   * Create a new Canton ledger client.
   * @param party - The party identity to act as (required)
   * @param urlOrConfig - Ledger URL string or LedgerConfig object
   * @param token - Auth token (only used when urlOrConfig is a string). Auto-generated if not provided.
   */
  constructor(
    party: Party,
    urlOrConfig?: string | Partial<LedgerConfig>,
    token?: string
  ) {
    if (!party) {
      throw new Error("Party is required to create a ledger client");
    }
    this.party = party;

    let resolvedUrl: string;
    let resolvedToken: string | undefined;
    let resolvedTimeout: number;
    let ledgerId: string | undefined;
    let applicationId: string | undefined;

    if (typeof urlOrConfig === "string") {
      resolvedUrl = urlOrConfig;
      resolvedToken = token;
      resolvedTimeout = defaultConfig.timeout ?? 30000;
    } else {
      const config = { ...defaultConfig, ...urlOrConfig };
      resolvedUrl = config.ledgerUrl ?? `http://${config.host}:${config.port}`;
      resolvedToken = config.token;
      resolvedTimeout = config.timeout ?? 30000;
      ledgerId = config.ledgerId;
      applicationId = config.applicationId;
    }

    // Normalize to avoid double slashes when concatenating paths
    this.baseUrl = resolvedUrl.endsWith("/")
      ? resolvedUrl.slice(0, -1)
      : resolvedUrl;
    this.timeout = resolvedTimeout;

    // Auto-generate JWT if no token provided (required for Canton sandbox)
    const authToken =
      resolvedToken || createJwtToken(party, { ledgerId, applicationId });

    this.headers = {
      "Content-Type": "application/json",
      Authorization: `Bearer ${authToken}`,
    };

    // Use shared package resolver for efficient caching across clients
    this.resolver = getPackageResolver();
  }

  /** Get the party this client is acting as */
  getParty(): Party {
    return this.party;
  }

  /** Get the package resolver for advanced usage */
  getResolver(): PackageResolver {
    return this.resolver;
  }

  /**
   * Resolve a template ID from package name format to package hash format.
   * Called automatically by query, create, and exercise methods.
   */
  private async resolveTemplateId(templateId: string): Promise<string> {
    return this.resolver.resolveTemplateId(
      templateId,
      this.baseUrl,
      this.headers
    );
  }

  /**
   * Perform a JSON API request with timeout, returning the unwrapped result.
   * The JSON API wraps responses in { status, result } or { status, errors }.
   */
  private async requestJson<T>(path: string, init: RequestInit): Promise<T> {
    const controller = new AbortController();
    const timeoutMs = Math.max(1, this.timeout || 30000);
    const timer = setTimeout(() => controller.abort(), timeoutMs);

    try {
      const response = await fetch(this.baseUrl + path, {
        ...init,
        headers: {
          ...this.headers,
          ...(init.headers as Record<string, string> | undefined),
        },
        signal: controller.signal,
      });

      const text = await response.text();
      let payload: unknown = null;
      if (text) {
        try {
          payload = JSON.parse(text);
        } catch {
          payload = text;
        }
      }

      const unwrap = (obj: unknown): unknown => {
        if (
          obj &&
          typeof obj === "object" &&
          "result" in (obj as Record<string, unknown>)
        ) {
          return (obj as { result: unknown }).result;
        }
        return obj;
      };

      // Some JSON API deployments return 200 with an errors field.
      // Treat that as a failure even if HTTP status is OK.
      if (payload && typeof payload === "object") {
        const record = payload as Record<string, unknown>;
        if ("errors" in record && record.errors) {
          throw new LedgerError(
            path + " failed: " + JSON.stringify(record.errors),
            LedgerErrorCode.INVALID_ARGUMENT,
            record.errors
          );
        }
      }

      if (!response.ok) {
        const details = payload;
        const msg = (() => {
          if (details && typeof details === "object") {
            const record = details as Record<string, unknown>;
            if ("errors" in record) return JSON.stringify(record.errors);
            if ("ledgerApiError" in record)
              return JSON.stringify(record.ledgerApiError);
          }
          return typeof details === "string"
            ? details
            : JSON.stringify(details);
        })();

        if (response.status === 401 || response.status === 403) {
          throw new UnauthorizedError(
            msg || "Unauthorized (" + response.status + ")",
            details
          );
        }
        if (response.status === 504) {
          throw new TimeoutError(msg || "Request timed out", details);
        }

        const code =
          response.status >= 500
            ? LedgerErrorCode.CONNECTION_FAILED
            : LedgerErrorCode.INVALID_ARGUMENT;

        throw new LedgerError(
          path + " failed: " + response.status + " - " + msg,
          code,
          details
        );
      }

      return unwrap(payload) as T;
    } catch (error) {
      if (error instanceof LedgerError) {
        throw error;
      }

      if (
        error &&
        typeof error === "object" &&
        (error as { name?: string }).name === "AbortError"
      ) {
        throw new TimeoutError("Request timed out");
      }

      throw new ConnectionError("Network error connecting to ledger", error);
    } finally {
      clearTimeout(timer);
    }
  }

  /**
   * Query contracts by template ID with optional filter.
   * Template IDs are automatically resolved from package names to hashes.
   */
  async query<T>(
    templateId: string,
    filter?: Partial<T>
  ): Promise<Contract<T>[]> {
    // Resolve package name to hash
    const resolvedTemplateId = await this.resolveTemplateId(templateId);

    const result = await this.requestJson<
      Array<{ contractId: string; payload: T; createdAt?: string }>
    >("/v1/query", {
      method: "POST",
      body: JSON.stringify({
        templateIds: [resolvedTemplateId],
        query: filter || {},
      }),
    });

    return (result || []).map((item) => ({
      contractId: item.contractId as ContractId<T>,
      payload: item.payload,
      createdAt: item.createdAt,
    }));
  }

  /**
   * Create a new contract.
   * Template IDs are automatically resolved from package names to hashes.
   */
  async create<T>(templateId: string, payload: T): Promise<ContractId<T>> {
    // Resolve package name to hash
    const resolvedTemplateId = await this.resolveTemplateId(templateId);

    const result = await this.requestJson<{ contractId: string }>(
      "/v1/create",
      {
        method: "POST",
        body: JSON.stringify({
          templateId: resolvedTemplateId,
          payload,
          meta: {
            actAs: [this.party],
          },
        }),
      }
    );

    return result.contractId as ContractId<T>;
  }

  /**
   * Exercise a choice on a contract.
   * Template IDs are automatically resolved from package names to hashes.
   */
  async exercise<T, R>(
    templateId: string,
    contractId: ContractId<T>,
    choice: string,
    args: unknown
  ): Promise<ExerciseResult<R>> {
    // Resolve package name to hash
    const resolvedTemplateId = await this.resolveTemplateId(templateId);

    const data = await this.requestJson<{
      exerciseResult: R;
      events?: unknown[];
    }>("/v1/exercise", {
      method: "POST",
      body: JSON.stringify({
        templateId: resolvedTemplateId,
        contractId,
        choice,
        argument: args,
        meta: {
          actAs: [this.party],
        },
      }),
    });

    return {
      exerciseResult: data.exerciseResult,
      events: data.events || [],
    };
  }

  /**
   * Fetch a specific contract by ID.
   */
  async fetch<T>(contractId: ContractId<T>): Promise<Contract<T> | null> {
    // JSON API returns 200 with { result: null } when not found
    const data = await this.requestJson<{
      contractId: string;
      payload: T;
      createdAt?: string;
    } | null>("/v1/fetch", {
      method: "POST",
      body: JSON.stringify({ contractId }),
    });

    if (!data) return null;
    return {
      contractId: data.contractId as ContractId<T>,
      payload: data.payload,
      createdAt: data.createdAt,
    };
  }
}

// ═══════════════════════════════════════════════════════════════
// HELPER FUNCTIONS
// ═══════════════════════════════════════════════════════════════

/**
 * Create a ledger client using configuration.
 * @param party - The party identity to act as (required)
 * @param config - Optional configuration (defaults to localhost:7575)
 */
export function createLedgerClient(
  party: Party,
  config?: Partial<LedgerConfig>
): CantonLedgerClient {
  const fullConfig = createConfig(config);
  return new CantonLedgerClient(party, fullConfig);
}

/**
 * Check if the ledger is reachable.
 * @param config - Configuration to use for the request
 */
export async function isLedgerReachable(
  config?: Partial<LedgerConfig>
): Promise<boolean> {
  try {
    const fullConfig = createConfig(config);
    // Generate JWT if no token provided (required for Canton sandbox)
    const token =
      fullConfig.token ||
      createJwtToken("admin", {
        ledgerId: fullConfig.ledgerId,
        applicationId: fullConfig.applicationId,
      });
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    };
    const response = await fetch(`${fullConfig.ledgerUrl}/v1/parties`, {
      method: "GET",
      headers,
    });
    return response.ok;
  } catch {
    return false;
  }
}

/**
 * Get all parties from the ledger.
 * @param config - Configuration to use for the request
 */
export async function getParties(
  config?: Partial<LedgerConfig>
): Promise<Party[]> {
  const fullConfig = createConfig(config);
  // Generate JWT if no token provided (required for Canton sandbox)
  const token =
    fullConfig.token ||
    createJwtToken("admin", {
      ledgerId: fullConfig.ledgerId,
      applicationId: fullConfig.applicationId,
    });
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    Authorization: `Bearer ${token}`,
  };
  const response = await fetch(`${fullConfig.ledgerUrl}/v1/parties`, {
    method: "GET",
    headers,
  });

  if (!response.ok) {
    throw new Error(`Failed to get parties: ${response.status}`);
  }

  // Canton returns objects with identifier, not plain strings
  interface PartyInfo {
    identifier: string;
    isLocal?: boolean;
  }
  const data = (await response.json()) as { result?: PartyInfo[] };
  return (data.result || []).map((p) => p.identifier as Party);
}

/**
 * Generate a unique ID for test isolation.
 */
export function uniqueId(prefix: string = "test"): string {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

/**
 * Resolve a party name to its full party identifier.
 *
 * Canton party identifiers have the format "Name::1220abc...".
 * This function takes a simple name like "Alice" and resolves it
 * to the full identifier by querying the ledger.
 *
 * @param partyName - Simple party name (e.g., "Alice") or full identifier
 * @param config - Optional ledger configuration
 * @returns Full party identifier (e.g., "Alice::1220abc...")
 * @throws Error if party is not found on the ledger
 *
 * @example
 * \`\`\`ts
 * // Resolve simple name to full identifier
 * const alice = await resolveParty('Alice');
 * // Returns: "Alice::1220cc28a614..."
 *
 * // Already a full identifier? Returns as-is
 * const bob = await resolveParty('Bob::1220abc...');
 * // Returns: "Bob::1220abc..."
 * \`\`\`
 */
export async function resolveParty(
  partyName: string,
  config?: Partial<LedgerConfig>
): Promise<Party> {
  // If already a full identifier (contains ::), return as-is
  if (partyName.includes("::")) {
    return partyName as Party;
  }

  // Query all parties from the ledger
  const allParties = await getParties(config);

  // Find party that starts with the name
  const match = allParties.find((p) => p.startsWith(`${partyName}::`));
  if (!match) {
    throw new Error(
      `Party '${partyName}' not found on ledger. ` +
        `Available parties: ${allParties.join(", ")}`
    );
  }

  return match;
}
