// ledger/config.ts
// Canton Ledger Configuration
// DO NOT EDIT - Generated by generate-canton-api.ts

// ═══════════════════════════════════════════════════════════════
// CONFIGURATION TYPES
// ═══════════════════════════════════════════════════════════════

/**
 * Canton ledger connection configuration.
 * Pass these values when creating a ledger client.
 */
export interface LedgerConfig {
  /** Ledger JSON API host (default: localhost) */
  host: string;
  /** Ledger JSON API port (default: 7575) */
  port: number;
  /** Full ledger URL (computed from host:port if not provided) */
  ledgerUrl?: string;
  /** Authentication token (optional - auto-generated if not provided) */
  token?: string;
  /** Request timeout in milliseconds (default: 30000) */
  timeout?: number;
  /** Ledger ID for JWT claims (default: sandbox) */
  ledgerId?: string;
  /** Application ID for JWT claims (default: lunar-dollar-sdk) */
  applicationId?: string;
}

/**
 * Create a ledger configuration with defaults.
 */
export function createConfig(options: Partial<LedgerConfig> = {}): LedgerConfig {
  const host = options.host ?? 'localhost';
  const port = options.port ?? 7575;
  return {
    host,
    port,
    ledgerUrl: options.ledgerUrl ?? `http://${host}:${port}`,
    token: options.token,
    timeout: options.timeout ?? 30000,
    ledgerId: options.ledgerId ?? 'sandbox',
    applicationId: options.applicationId ?? 'lunar-dollar-sdk',
  };
}

/**
 * Default configuration for local development.
 */
export const defaultConfig: LedgerConfig = createConfig();

/**
 * Create config from environment variables (Node.js only).
 * Use this in Node.js environments where process.env is available.
 */
export function createConfigFromEnv(): LedgerConfig {
  const env = typeof process !== 'undefined' ? process.env : {};
  return createConfig({
    host: env.LEDGER_HOST || 'localhost',
    port: parseInt(env.LEDGER_PORT || '7575', 10),
    token: env.LEDGER_TOKEN,
    timeout: env.LEDGER_TIMEOUT ? parseInt(env.LEDGER_TIMEOUT, 10) : undefined,
    ledgerId: env.LEDGER_ID || 'sandbox',
    applicationId: env.APPLICATION_ID || 'lunar-dollar-sdk',
  });
}

// ═══════════════════════════════════════════════════════════════
// JWT AUTHENTICATION
// ═══════════════════════════════════════════════════════════════

/**
 * Options for JWT token generation.
 */
export interface JwtOptions {
  /** Ledger ID - must match Canton config (default: "sandbox") */
  ledgerId?: string;
  /** Application identifier (default: "lunar-dollar-sdk") */
  applicationId?: string;
  /** Token expiration in seconds (default: 86400 = 24h) */
  expiresIn?: number;
}

/**
 * Generate an unsigned JWT for Canton sandbox authentication.
 * 
 * Canton JSON API requires JWTs with Daml-specific claims under the
 * "https://daml.com/ledger-api" namespace.
 * 
 * WARNING: This generates unsigned tokens suitable only for development.
 * Production deployments require properly signed JWTs.
 * 
 * @param party - The party ID to act as (e.g., "Alice::1220abc...")
 * @param options - JWT configuration options
 * @returns JWT token string in format "header.payload." (trailing dot for empty signature)
 * 
 * @example
 * const token = createJwtToken('Alice::1220abc123');
 * // Use with ledger client
 * const ledger = new CantonLedgerClient(party, { token });
 */
export function createJwtToken(party: string, options: JwtOptions = {}): string {
  const header = { alg: 'none', typ: 'JWT' };
  
  const payload = {
    'https://daml.com/ledger-api': {
      ledgerId: options.ledgerId || 'sandbox',
      actAs: [party],
      readAs: [party],
      applicationId: options.applicationId || 'lunar-dollar-sdk',
    },
    exp: Math.floor(Date.now() / 1000) + (options.expiresIn || 86400),
    iat: Math.floor(Date.now() / 1000),
  };
  
  // Base64url encoding (NOT standard base64!)
  // Must replace: = with nothing, + with -, / with _
  const base64url = (obj: unknown): string => {
    const json = JSON.stringify(obj);
    const g = globalThis as any;
    let base64: string;
    if (g.Buffer?.from) {
      base64 = g.Buffer.from(json, 'utf8').toString('base64');
    } else if (typeof btoa !== 'undefined') {
      // btoa expects latin1; encode UTF-8 first
      base64 = btoa(unescape(encodeURIComponent(json)));
    } else {
      throw new Error('No base64 encoder available');
    }
    return base64.replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');
  };
  
  // Format: header.payload. (trailing dot = empty signature, required!)
  return `${base64url(header)}.${base64url(payload)}.`;
}
