// ledger/errors.ts
// Typed error classes for ledger operations
// DO NOT EDIT - Generated by generate-canton-api.ts

export enum LedgerErrorCode {
  CONNECTION_FAILED = 'CONNECTION_FAILED',
  TIMEOUT = 'TIMEOUT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  CONTRACT_NOT_FOUND = 'CONTRACT_NOT_FOUND',
  EXERCISE_FAILED = 'EXERCISE_FAILED',
  INVALID_ARGUMENT = 'INVALID_ARGUMENT',
  NETWORK_ERROR = 'NETWORK_ERROR',
}

export class LedgerError extends Error {
  constructor(
    message: string,
    public readonly code: LedgerErrorCode,
    public readonly details?: unknown,
    public readonly originalError?: Error
  ) {
    super(message);
    this.name = 'LedgerError';
  }

  /** Convert ledger error to user-friendly message */
  toUserFriendlyMessage(): string {
    switch (this.code) {
      case LedgerErrorCode.CONNECTION_FAILED:
        return 'Unable to connect to ledger. Check connection settings.';
      case LedgerErrorCode.TIMEOUT:
        return 'Request timed out. Ledger may be slow or unavailable.';
      case LedgerErrorCode.UNAUTHORIZED:
        return 'Authentication failed. Check token or permissions.';
      case LedgerErrorCode.CONTRACT_NOT_FOUND:
        return `Contract not found. It may have been archived or you lack visibility.`;
      case LedgerErrorCode.EXERCISE_FAILED:
        return this.parseExerciseError() || 'Failed to execute choice. Check arguments and permissions.';
      case LedgerErrorCode.INVALID_ARGUMENT:
        return 'Invalid arguments provided. Check types and required fields.';
      case LedgerErrorCode.NETWORK_ERROR:
        return 'Network error. Check connectivity.';
      default:
        return this.message;
    }
  }

  /** Parse Canton exercise error for meaningful context */
  private parseExerciseError(): string | null {
    const msg = this.message.toLowerCase();
    if (msg.includes('authorization')) return 'Insufficient authorization. Missing signatory or controller.';
    if (msg.includes('contract not active')) return 'Contract is archived or locked.';
    if (msg.includes('missing field')) return 'Required field missing in arguments.';
    if (msg.includes('type mismatch')) return 'Argument type mismatch. Check value types.';
    if (msg.includes('precondition failed')) return 'Choice precondition not met. Check contract state.';
    return null;
  }
}

export class ConnectionError extends LedgerError {
  constructor(message: string, details?: unknown) {
    super(message, LedgerErrorCode.CONNECTION_FAILED, details);
    this.name = 'ConnectionError';
  }
}

export class TimeoutError extends LedgerError {
  constructor(message: string = 'Request timed out', details?: unknown) {
    super(message, LedgerErrorCode.TIMEOUT, details);
    this.name = 'TimeoutError';
  }
}

export class UnauthorizedError extends LedgerError {
  constructor(message: string = 'Unauthorized', details?: unknown) {
    super(message, LedgerErrorCode.UNAUTHORIZED, details);
    this.name = 'UnauthorizedError';
  }
}

export class ContractNotFoundError extends LedgerError {
  constructor(contractId: string) {
    super(`Contract not found: ${contractId}`, LedgerErrorCode.CONTRACT_NOT_FOUND, { contractId });
    this.name = 'ContractNotFoundError';
  }
}

export class ExerciseError extends LedgerError {
  constructor(message: string, details?: unknown) {
    super(message, LedgerErrorCode.EXERCISE_FAILED, details);
    this.name = 'ExerciseError';
  }
}

export function isLedgerError(error: unknown): error is LedgerError {
  return error instanceof LedgerError;
}

export function isRetryable(error: unknown): boolean {
  if (!isLedgerError(error)) return false;
  return [
    LedgerErrorCode.CONNECTION_FAILED,
    LedgerErrorCode.TIMEOUT,
    LedgerErrorCode.NETWORK_ERROR,
  ].includes(error.code);
}
