// react/hooks/core.ts
// Core generic hooks for contract operations
// DO NOT EDIT - Generated by generate-canton-react.ts

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import type { UseQueryResult, UseMutationResult, QueryKey } from '@tanstack/react-query';
import { useLedger } from '../context/useLedger';
import type { Contract, ContractId, ExerciseResult } from '../../core';

export function useContractQuery<T>(
  templateId: string,
  filter?: Partial<T>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<T>[]> {
  const { ledger } = useLedger();

  return useQuery({
    queryKey: ['contracts', templateId, filter] as const,
    queryFn: () => ledger.query<T>(templateId, filter),
    enabled: options?.enabled ?? true,
  });
}

export function useContractMutation<T>(
  templateId: string,
  options?: {
    onSuccess?: (contractId: ContractId<T>) => void;
    invalidateQueries?: QueryKey[];
  }
): UseMutationResult<ContractId<T>, Error, T> {
  const { ledger } = useLedger();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (payload: T) => ledger.create<T>(templateId, payload),
    onSuccess: (contractId: ContractId<T>) => {
      options?.onSuccess?.(contractId);
      options?.invalidateQueries?.forEach((key: QueryKey) => {
        queryClient.invalidateQueries({ queryKey: key });
      });
    },
  });
}

/** Mutation input for choice execution */
export interface ChoiceMutationInput<TArgs = Record<string, never>> {
  contractId: string;
  args?: TArgs;
}

export function useChoiceMutation<TArgs = Record<string, never>, TResult = unknown>(
  templateId: string,
  choice: string,
  options?: {
    onSuccess?: (result: ExerciseResult<TResult>) => void;
    invalidateQueries?: QueryKey[];
  }
): UseMutationResult<ExerciseResult<TResult>, Error, ChoiceMutationInput<TArgs>> {
  const { ledger } = useLedger();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (input: ChoiceMutationInput<TArgs>) =>
      ledger.exercise<unknown, TResult>(
        templateId,
        input.contractId as ContractId<unknown>,
        choice,
        input.args ?? {}
      ),
    onSuccess: (result: ExerciseResult<TResult>) => {
      options?.onSuccess?.(result);
      options?.invalidateQueries?.forEach((key: QueryKey) => {
        queryClient.invalidateQueries({ queryKey: key });
      });
    },
  });
}

/** Simplified mutation for choices without arguments */
export function useSimpleChoiceMutation<TResult = unknown>(
  templateId: string,
  choice: string,
  options?: {
    onSuccess?: (result: ExerciseResult<TResult>) => void;
    invalidateQueries?: QueryKey[];
  }
): UseMutationResult<ExerciseResult<TResult>, Error, string> {
  const { ledger } = useLedger();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (contractId: string) =>
      ledger.exercise<unknown, TResult>(
        templateId,
        contractId as ContractId<unknown>,
        choice,
        {}
      ),
    onSuccess: (result: ExerciseResult<TResult>) => {
      options?.onSuccess?.(result);
      options?.invalidateQueries?.forEach((key: QueryKey) => {
        queryClient.invalidateQueries({ queryKey: key });
      });
    },
  });
}
