// react/hooks/keys.ts
// Query key factories for cache management
// DO NOT EDIT - Generated by generate-canton-react.ts

import type { QueryKey } from '@tanstack/react-query';
import { TemplateIds } from '../../lunar-dollar-api';

// These keys are intentionally shaped to match react/hooks/core.ts:
// queryKey: ['contracts', templateId, filter]

export const queryKeys = {
  /** Query keys for Account_Account_Factory */
  factory: {
    all: ['contracts', TemplateIds.Account_Account_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Account_Account_Factory, filter],
  },
  /** Query keys for Account */
  account: {
    all: ['contracts', TemplateIds.Account] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Account, filter],
  },
  /** Query keys for Claims_Lifecycle_Rule */
  rule: {
    all: ['contracts', TemplateIds.Claims_Lifecycle_Rule] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Claims_Lifecycle_Rule, filter],
  },
  /** Query keys for Data_Numeric_Observation_Factory */
  observationFactory: {
    all: ['contracts', TemplateIds.Data_Numeric_Observation_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Data_Numeric_Observation_Factory, filter],
  },
  /** Query keys for Data_Numeric_Observation */
  observation: {
    all: ['contracts', TemplateIds.Data_Numeric_Observation] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Data_Numeric_Observation, filter],
  },
  /** Query keys for Data_Reference_HolidayCalendar_Factory */
  holidayCalendarFactory: {
    all: ['contracts', TemplateIds.Data_Reference_HolidayCalendar_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Data_Reference_HolidayCalendar_Factory, filter],
  },
  /** Query keys for Data_Reference_HolidayCalendar */
  holidayCalendar: {
    all: ['contracts', TemplateIds.Data_Reference_HolidayCalendar] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Data_Reference_HolidayCalendar, filter],
  },
  /** Query keys for Data_Time_DateClock */
  dateClock: {
    all: ['contracts', TemplateIds.Data_Time_DateClock] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Data_Time_DateClock, filter],
  },
  /** Query keys for Data_Time_DateClockUpdate_DateClockUpdateEvent */
  dateClockUpdateEvent: {
    all: ['contracts', TemplateIds.Data_Time_DateClockUpdate_DateClockUpdateEvent] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Data_Time_DateClockUpdate_DateClockUpdateEvent, filter],
  },
  /** Query keys for Data_Time_LedgerTime */
  ledgerTime: {
    all: ['contracts', TemplateIds.Data_Time_LedgerTime] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Data_Time_LedgerTime, filter],
  },
  /** Query keys for Holding_BaseHolding */
  baseHolding: {
    all: ['contracts', TemplateIds.Holding_BaseHolding] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Holding_BaseHolding, filter],
  },
  /** Query keys for Holding_Factory */
  holdingFactory: {
    all: ['contracts', TemplateIds.Holding_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Holding_Factory, filter],
  },
  /** Query keys for Holding_Fungible */
  fungible: {
    all: ['contracts', TemplateIds.Holding_Fungible] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Holding_Fungible, filter],
  },
  /** Query keys for Holding_Transferable */
  transferable: {
    all: ['contracts', TemplateIds.Holding_Transferable] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Holding_Transferable, filter],
  },
  /** Query keys for Holding_TransferableFungible */
  transferableFungible: {
    all: ['contracts', TemplateIds.Holding_TransferableFungible] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Holding_TransferableFungible, filter],
  },
  /** Query keys for Bond_Callable_Factory */
  callableFactory: {
    all: ['contracts', TemplateIds.Bond_Callable_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Bond_Callable_Factory, filter],
  },
  /** Query keys for Bond_Callable_Instrument */
  instrument: {
    all: ['contracts', TemplateIds.Bond_Callable_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Bond_Callable_Instrument, filter],
  },
  /** Query keys for Bond_FixedRate_Factory */
  fixedRateFactory: {
    all: ['contracts', TemplateIds.Bond_FixedRate_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Bond_FixedRate_Factory, filter],
  },
  /** Query keys for Bond_FixedRate_Instrument */
  fixedRateInstrument: {
    all: ['contracts', TemplateIds.Bond_FixedRate_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Bond_FixedRate_Instrument, filter],
  },
  /** Query keys for Bond_FloatingRate_Factory */
  floatingRateFactory: {
    all: ['contracts', TemplateIds.Bond_FloatingRate_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Bond_FloatingRate_Factory, filter],
  },
  /** Query keys for Bond_FloatingRate_Instrument */
  floatingRateInstrument: {
    all: ['contracts', TemplateIds.Bond_FloatingRate_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Bond_FloatingRate_Instrument, filter],
  },
  /** Query keys for Bond_InflationLinked_Factory */
  inflationLinkedFactory: {
    all: ['contracts', TemplateIds.Bond_InflationLinked_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Bond_InflationLinked_Factory, filter],
  },
  /** Query keys for Bond_InflationLinked_Instrument */
  inflationLinkedInstrument: {
    all: ['contracts', TemplateIds.Bond_InflationLinked_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Bond_InflationLinked_Instrument, filter],
  },
  /** Query keys for Bond_ZeroCoupon_Factory */
  zeroCouponFactory: {
    all: ['contracts', TemplateIds.Bond_ZeroCoupon_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Bond_ZeroCoupon_Factory, filter],
  },
  /** Query keys for Bond_ZeroCoupon_Instrument */
  zeroCouponInstrument: {
    all: ['contracts', TemplateIds.Bond_ZeroCoupon_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Bond_ZeroCoupon_Instrument, filter],
  },
  /** Query keys for Equity_Factory */
  equityFactory: {
    all: ['contracts', TemplateIds.Equity_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Equity_Factory, filter],
  },
  /** Query keys for Equity_Instrument */
  equityInstrument: {
    all: ['contracts', TemplateIds.Equity_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Equity_Instrument, filter],
  },
  /** Query keys for Generic_Factory */
  genericFactory: {
    all: ['contracts', TemplateIds.Generic_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Generic_Factory, filter],
  },
  /** Query keys for Generic_Instrument */
  genericInstrument: {
    all: ['contracts', TemplateIds.Generic_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Generic_Instrument, filter],
  },
  /** Query keys for Generic_Lifecycle_Rule */
  lifecycleRule: {
    all: ['contracts', TemplateIds.Generic_Lifecycle_Rule] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Generic_Lifecycle_Rule, filter],
  },
  /** Query keys for Option_BarrierEuropeanCash_Factory */
  barrierEuropeanCashFactory: {
    all: ['contracts', TemplateIds.Option_BarrierEuropeanCash_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Option_BarrierEuropeanCash_Factory, filter],
  },
  /** Query keys for Option_BarrierEuropeanCash_Instrument */
  barrierEuropeanCashInstrument: {
    all: ['contracts', TemplateIds.Option_BarrierEuropeanCash_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Option_BarrierEuropeanCash_Instrument, filter],
  },
  /** Query keys for Option_Dividend_Election_Factory */
  electionFactory: {
    all: ['contracts', TemplateIds.Option_Dividend_Election_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Option_Dividend_Election_Factory, filter],
  },
  /** Query keys for Option_Dividend_Factory */
  dividendFactory: {
    all: ['contracts', TemplateIds.Option_Dividend_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Option_Dividend_Factory, filter],
  },
  /** Query keys for Option_Dividend_Instrument */
  dividendInstrument: {
    all: ['contracts', TemplateIds.Option_Dividend_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Option_Dividend_Instrument, filter],
  },
  /** Query keys for Option_EuropeanCash_Factory */
  europeanCashFactory: {
    all: ['contracts', TemplateIds.Option_EuropeanCash_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Option_EuropeanCash_Factory, filter],
  },
  /** Query keys for Option_EuropeanCash_Instrument */
  europeanCashInstrument: {
    all: ['contracts', TemplateIds.Option_EuropeanCash_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Option_EuropeanCash_Instrument, filter],
  },
  /** Query keys for Option_EuropeanPhysical_Factory */
  europeanPhysicalFactory: {
    all: ['contracts', TemplateIds.Option_EuropeanPhysical_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Option_EuropeanPhysical_Factory, filter],
  },
  /** Query keys for Option_EuropeanPhysical_Instrument */
  europeanPhysicalInstrument: {
    all: ['contracts', TemplateIds.Option_EuropeanPhysical_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Option_EuropeanPhysical_Instrument, filter],
  },
  /** Query keys for StructuredProduct_AutoCallable_Factory */
  autoCallableFactory: {
    all: ['contracts', TemplateIds.StructuredProduct_AutoCallable_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.StructuredProduct_AutoCallable_Factory, filter],
  },
  /** Query keys for StructuredProduct_AutoCallable_Instrument */
  autoCallableInstrument: {
    all: ['contracts', TemplateIds.StructuredProduct_AutoCallable_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.StructuredProduct_AutoCallable_Instrument, filter],
  },
  /** Query keys for StructuredProduct_BarrierReverseConvertible_Factory */
  barrierReverseConvertibleFactory: {
    all: ['contracts', TemplateIds.StructuredProduct_BarrierReverseConvertible_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.StructuredProduct_BarrierReverseConvertible_Factory, filter],
  },
  /** Query keys for StructuredProduct_BarrierReverseConvertible_Instrument */
  barrierReverseConvertibleInstrument: {
    all: ['contracts', TemplateIds.StructuredProduct_BarrierReverseConvertible_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.StructuredProduct_BarrierReverseConvertible_Instrument, filter],
  },
  /** Query keys for Swap_Asset_DistributionRule */
  distributionRule: {
    all: ['contracts', TemplateIds.Swap_Asset_DistributionRule] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Swap_Asset_DistributionRule, filter],
  },
  /** Query keys for Swap_Asset_Factory */
  assetFactory: {
    all: ['contracts', TemplateIds.Swap_Asset_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Swap_Asset_Factory, filter],
  },
  /** Query keys for Swap_Asset_Instrument */
  assetInstrument: {
    all: ['contracts', TemplateIds.Swap_Asset_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Swap_Asset_Instrument, filter],
  },
  /** Query keys for Swap_CreditDefault_Factory */
  creditDefaultFactory: {
    all: ['contracts', TemplateIds.Swap_CreditDefault_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Swap_CreditDefault_Factory, filter],
  },
  /** Query keys for Swap_CreditDefault_Instrument */
  creditDefaultInstrument: {
    all: ['contracts', TemplateIds.Swap_CreditDefault_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Swap_CreditDefault_Instrument, filter],
  },
  /** Query keys for Swap_Currency_Factory */
  currencyFactory: {
    all: ['contracts', TemplateIds.Swap_Currency_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Swap_Currency_Factory, filter],
  },
  /** Query keys for Swap_Currency_Instrument */
  currencyInstrument: {
    all: ['contracts', TemplateIds.Swap_Currency_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Swap_Currency_Instrument, filter],
  },
  /** Query keys for Swap_ForeignExchange_Factory */
  foreignExchangeFactory: {
    all: ['contracts', TemplateIds.Swap_ForeignExchange_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Swap_ForeignExchange_Factory, filter],
  },
  /** Query keys for Swap_ForeignExchange_Instrument */
  foreignExchangeInstrument: {
    all: ['contracts', TemplateIds.Swap_ForeignExchange_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Swap_ForeignExchange_Instrument, filter],
  },
  /** Query keys for Swap_Fpml_Factory */
  fpmlFactory: {
    all: ['contracts', TemplateIds.Swap_Fpml_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Swap_Fpml_Factory, filter],
  },
  /** Query keys for Swap_Fpml_Instrument */
  fpmlInstrument: {
    all: ['contracts', TemplateIds.Swap_Fpml_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Swap_Fpml_Instrument, filter],
  },
  /** Query keys for Swap_InterestRate_Factory */
  interestRateFactory: {
    all: ['contracts', TemplateIds.Swap_InterestRate_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Swap_InterestRate_Factory, filter],
  },
  /** Query keys for Swap_InterestRate_Instrument */
  interestRateInstrument: {
    all: ['contracts', TemplateIds.Swap_InterestRate_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Swap_InterestRate_Instrument, filter],
  },
  /** Query keys for Token_Factory */
  tokenFactory: {
    all: ['contracts', TemplateIds.Token_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Token_Factory, filter],
  },
  /** Query keys for Token_Instrument */
  tokenInstrument: {
    all: ['contracts', TemplateIds.Token_Instrument] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Token_Instrument, filter],
  },
  /** Query keys for Account_Account_Reference */
  reference: {
    all: ['contracts', TemplateIds.Account_Account_Reference] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Account_Account_Reference, filter],
  },
  /** Query keys for Holding_Factory_Reference */
  factoryReference: {
    all: ['contracts', TemplateIds.Holding_Factory_Reference] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Holding_Factory_Reference, filter],
  },
  /** Query keys for Base_Instrument_Reference */
  instrumentReference: {
    all: ['contracts', TemplateIds.Base_Instrument_Reference] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Base_Instrument_Reference, filter],
  },
  /** Query keys for Lifecycle_Effect */
  effect: {
    all: ['contracts', TemplateIds.Lifecycle_Effect] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Lifecycle_Effect, filter],
  },
  /** Query keys for Lifecycle_Election_Factory */
  lifecycleElectionFactory: {
    all: ['contracts', TemplateIds.Lifecycle_Election_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Lifecycle_Election_Factory, filter],
  },
  /** Query keys for Lifecycle_Election */
  election: {
    all: ['contracts', TemplateIds.Lifecycle_Election] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Lifecycle_Election, filter],
  },
  /** Query keys for Lifecycle_ElectionEffect */
  electionEffect: {
    all: ['contracts', TemplateIds.Lifecycle_ElectionEffect] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Lifecycle_ElectionEffect, filter],
  },
  /** Query keys for Lifecycle_Distribution_Event */
  event: {
    all: ['contracts', TemplateIds.Lifecycle_Distribution_Event] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Lifecycle_Distribution_Event, filter],
  },
  /** Query keys for Lifecycle_Replacement_Event */
  replacementEvent: {
    all: ['contracts', TemplateIds.Lifecycle_Replacement_Event] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Lifecycle_Replacement_Event, filter],
  },
  /** Query keys for Lifecycle_Claim_Rule */
  claimRule: {
    all: ['contracts', TemplateIds.Lifecycle_Claim_Rule] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Lifecycle_Claim_Rule, filter],
  },
  /** Query keys for Lifecycle_Distribution_Rule */
  lifecycleDistributionRule: {
    all: ['contracts', TemplateIds.Lifecycle_Distribution_Rule] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Lifecycle_Distribution_Rule, filter],
  },
  /** Query keys for Lifecycle_Replacement_Rule */
  replacementRule: {
    all: ['contracts', TemplateIds.Lifecycle_Replacement_Rule] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Lifecycle_Replacement_Rule, filter],
  },
  /** Query keys for Settlement_Batch */
  batch: {
    all: ['contracts', TemplateIds.Settlement_Batch] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Settlement_Batch, filter],
  },
  /** Query keys for Settlement_Factory */
  settlementFactory: {
    all: ['contracts', TemplateIds.Settlement_Factory] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Settlement_Factory, filter],
  },
  /** Query keys for Settlement_Instruction */
  instruction: {
    all: ['contracts', TemplateIds.Settlement_Instruction] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Settlement_Instruction, filter],
  },
  /** Query keys for Settlement_RouteProvider_IntermediatedStatic */
  intermediatedStatic: {
    all: ['contracts', TemplateIds.Settlement_RouteProvider_IntermediatedStatic] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Settlement_RouteProvider_IntermediatedStatic, filter],
  },
  /** Query keys for Settlement_RouteProvider_SingleCustodian */
  singleCustodian: {
    all: ['contracts', TemplateIds.Settlement_RouteProvider_SingleCustodian] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Settlement_RouteProvider_SingleCustodian, filter],
  },
  /** Query keys for LunarDollar */
  lunarDollar: {
    all: ['contracts', TemplateIds.LunarDollar] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.LunarDollar, filter],
  },
  /** Query keys for PaymentReceiver */
  paymentReceiver: {
    all: ['contracts', TemplateIds.PaymentReceiver] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.PaymentReceiver, filter],
  },
  /** Query keys for PaymentReceiver_AccessGrant */
  accessGrant: {
    all: ['contracts', TemplateIds.PaymentReceiver_AccessGrant] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.PaymentReceiver_AccessGrant, filter],
  },
  /** Query keys for TransferRequest */
  transferRequest: {
    all: ['contracts', TemplateIds.TransferRequest] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.TransferRequest, filter],
  },
  /** Query keys for Workflow_CreateAccount_Request */
  request: {
    all: ['contracts', TemplateIds.Workflow_CreateAccount_Request] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Workflow_CreateAccount_Request, filter],
  },
  /** Query keys for Workflow_CreditAccount_Request */
  creditAccountRequest: {
    all: ['contracts', TemplateIds.Workflow_CreditAccount_Request] as QueryKey,
    list: (filter?: unknown): QueryKey => ['contracts', TemplateIds.Workflow_CreditAccount_Request, filter],
  },
} as const;
