// react/hooks/mutations.ts
// Generated mutation hooks (action-first naming)
// DO NOT EDIT - Generated by generate-canton-react.ts

import { useContractMutation, useChoiceMutation, useSimpleChoiceMutation } from './core';
import { TemplateIds } from '../../lunar-dollar-api';
import type * as API from '../../lunar-dollar-api';
import type { Command } from '../../core';
import { queryKeys } from './keys';

type CommandResult<T> = T extends Command<infer R> ? R : unknown;

/** Create Factory contracts */
export function useCreateFactory() {
  return useContractMutation<API.Account_Account_Factory.Payload>(TemplateIds.Account_Account_Factory, {
    invalidateQueries: [queryKeys.factory.all],
  });
}

/** Grouped actions for Factory */
export function useFactoryActions() {
  const createMutation = useCreateFactory();

  return {
    /** Create Factory */
    create: (payload: API.Account_Account_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create Account contracts */
export function useCreateAccount() {
  return useContractMutation<API.Account.Payload>(TemplateIds.Account, {
    invalidateQueries: [queryKeys.account.all],
  });
}

/** Grouped actions for Account */
export function useAccountActions() {
  const createMutation = useCreateAccount();

  return {
    /** Create Account */
    create: (payload: API.Account.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create Rule contracts */
export function useCreateRule() {
  return useContractMutation<API.Claims_Lifecycle_Rule.Payload>(TemplateIds.Claims_Lifecycle_Rule, {
    invalidateQueries: [queryKeys.rule.all],
  });
}

/** Grouped actions for Rule */
export function useRuleActions() {
  const createMutation = useCreateRule();

  return {
    /** Create Rule */
    create: (payload: API.Claims_Lifecycle_Rule.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create ObservationFactory contracts */
export function useCreateObservationFactory() {
  return useContractMutation<API.Data_Numeric_Observation_Factory.Payload>(TemplateIds.Data_Numeric_Observation_Factory, {
    invalidateQueries: [queryKeys.observationFactory.all],
  });
}

/** Grouped actions for ObservationFactory */
export function useObservationFactoryActions() {
  const createMutation = useCreateObservationFactory();

  return {
    /** Create ObservationFactory */
    create: (payload: API.Data_Numeric_Observation_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create Observation contracts */
export function useCreateObservation() {
  return useContractMutation<API.Data_Numeric_Observation.Payload>(TemplateIds.Data_Numeric_Observation, {
    invalidateQueries: [queryKeys.observation.all],
  });
}

/** Grouped actions for Observation */
export function useObservationActions() {
  const createMutation = useCreateObservation();

  return {
    /** Create Observation */
    create: (payload: API.Data_Numeric_Observation.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create HolidayCalendarFactory contracts */
export function useCreateHolidayCalendarFactory() {
  return useContractMutation<API.Data_Reference_HolidayCalendar_Factory.Payload>(TemplateIds.Data_Reference_HolidayCalendar_Factory, {
    invalidateQueries: [queryKeys.holidayCalendarFactory.all],
  });
}

/** Grouped actions for HolidayCalendarFactory */
export function useHolidayCalendarFactoryActions() {
  const createMutation = useCreateHolidayCalendarFactory();

  return {
    /** Create HolidayCalendarFactory */
    create: (payload: API.Data_Reference_HolidayCalendar_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create HolidayCalendar contracts */
export function useCreateHolidayCalendar() {
  return useContractMutation<API.Data_Reference_HolidayCalendar.Payload>(TemplateIds.Data_Reference_HolidayCalendar, {
    invalidateQueries: [queryKeys.holidayCalendar.all],
  });
}

/** Exercise GetCalendar on HolidayCalendar */
export function useGetCalendarHolidayCalendar() {
  return useChoiceMutation<Parameters<typeof API.Data_Reference_HolidayCalendar.getCalendar>[1], CommandResult<ReturnType<typeof API.Data_Reference_HolidayCalendar.getCalendar>>>(
    TemplateIds.Data_Reference_HolidayCalendar,
    'GetCalendar',
    { invalidateQueries: [queryKeys.holidayCalendar.all] }
  );
}

/** Grouped actions for HolidayCalendar */
export function useHolidayCalendarActions() {
  const createMutation = useCreateHolidayCalendar();
  const getCalendarMutation = useGetCalendarHolidayCalendar();

  return {
    /** Create HolidayCalendar */
    create: (payload: API.Data_Reference_HolidayCalendar.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    /** GetCalendar */
    getCalendar: (contractId: string, args: Parameters<typeof API.Data_Reference_HolidayCalendar.getCalendar>[1]) =>
      getCalendarMutation.mutateAsync({ contractId, args }),
    isGetCalendaring: getCalendarMutation.isPending,
    error: createMutation.error || getCalendarMutation.error,
  };
}

/** Create DateClock contracts */
export function useCreateDateClock() {
  return useContractMutation<API.Data_Time_DateClock.Payload>(TemplateIds.Data_Time_DateClock, {
    invalidateQueries: [queryKeys.dateClock.all],
  });
}

/** Grouped actions for DateClock */
export function useDateClockActions() {
  const createMutation = useCreateDateClock();

  return {
    /** Create DateClock */
    create: (payload: API.Data_Time_DateClock.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create DateClockUpdateEvent contracts */
export function useCreateDateClockUpdateEvent() {
  return useContractMutation<API.Data_Time_DateClockUpdate_DateClockUpdateEvent.Payload>(TemplateIds.Data_Time_DateClockUpdate_DateClockUpdateEvent, {
    invalidateQueries: [queryKeys.dateClockUpdateEvent.all],
  });
}

/** Grouped actions for DateClockUpdateEvent */
export function useDateClockUpdateEventActions() {
  const createMutation = useCreateDateClockUpdateEvent();

  return {
    /** Create DateClockUpdateEvent */
    create: (payload: API.Data_Time_DateClockUpdate_DateClockUpdateEvent.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create LedgerTime contracts */
export function useCreateLedgerTime() {
  return useContractMutation<API.Data_Time_LedgerTime.Payload>(TemplateIds.Data_Time_LedgerTime, {
    invalidateQueries: [queryKeys.ledgerTime.all],
  });
}

/** Grouped actions for LedgerTime */
export function useLedgerTimeActions() {
  const createMutation = useCreateLedgerTime();

  return {
    /** Create LedgerTime */
    create: (payload: API.Data_Time_LedgerTime.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create BaseHolding contracts */
export function useCreateBaseHolding() {
  return useContractMutation<API.Holding_BaseHolding.Payload>(TemplateIds.Holding_BaseHolding, {
    invalidateQueries: [queryKeys.baseHolding.all],
  });
}

/** Grouped actions for BaseHolding */
export function useBaseHoldingActions() {
  const createMutation = useCreateBaseHolding();

  return {
    /** Create BaseHolding */
    create: (payload: API.Holding_BaseHolding.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create HoldingFactory contracts */
export function useCreateHoldingFactory() {
  return useContractMutation<API.Holding_Factory.Payload>(TemplateIds.Holding_Factory, {
    invalidateQueries: [queryKeys.holdingFactory.all],
  });
}

/** Grouped actions for HoldingFactory */
export function useHoldingFactoryActions() {
  const createMutation = useCreateHoldingFactory();

  return {
    /** Create HoldingFactory */
    create: (payload: API.Holding_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create Fungible contracts */
export function useCreateFungible() {
  return useContractMutation<API.Holding_Fungible.Payload>(TemplateIds.Holding_Fungible, {
    invalidateQueries: [queryKeys.fungible.all],
  });
}

/** Grouped actions for Fungible */
export function useFungibleActions() {
  const createMutation = useCreateFungible();

  return {
    /** Create Fungible */
    create: (payload: API.Holding_Fungible.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create Transferable contracts */
export function useCreateTransferable() {
  return useContractMutation<API.Holding_Transferable.Payload>(TemplateIds.Holding_Transferable, {
    invalidateQueries: [queryKeys.transferable.all],
  });
}

/** Grouped actions for Transferable */
export function useTransferableActions() {
  const createMutation = useCreateTransferable();

  return {
    /** Create Transferable */
    create: (payload: API.Holding_Transferable.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create TransferableFungible contracts */
export function useCreateTransferableFungible() {
  return useContractMutation<API.Holding_TransferableFungible.Payload>(TemplateIds.Holding_TransferableFungible, {
    invalidateQueries: [queryKeys.transferableFungible.all],
  });
}

/** Grouped actions for TransferableFungible */
export function useTransferableFungibleActions() {
  const createMutation = useCreateTransferableFungible();

  return {
    /** Create TransferableFungible */
    create: (payload: API.Holding_TransferableFungible.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create CallableFactory contracts */
export function useCreateCallableFactory() {
  return useContractMutation<API.Bond_Callable_Factory.Payload>(TemplateIds.Bond_Callable_Factory, {
    invalidateQueries: [queryKeys.callableFactory.all],
  });
}

/** Grouped actions for CallableFactory */
export function useCallableFactoryActions() {
  const createMutation = useCreateCallableFactory();

  return {
    /** Create CallableFactory */
    create: (payload: API.Bond_Callable_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create Instrument contracts */
export function useCreateInstrument() {
  return useContractMutation<API.Bond_Callable_Instrument.Payload>(TemplateIds.Bond_Callable_Instrument, {
    invalidateQueries: [queryKeys.instrument.all],
  });
}

/** Grouped actions for Instrument */
export function useInstrumentActions() {
  const createMutation = useCreateInstrument();

  return {
    /** Create Instrument */
    create: (payload: API.Bond_Callable_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create FixedRateFactory contracts */
export function useCreateFixedRateFactory() {
  return useContractMutation<API.Bond_FixedRate_Factory.Payload>(TemplateIds.Bond_FixedRate_Factory, {
    invalidateQueries: [queryKeys.fixedRateFactory.all],
  });
}

/** Grouped actions for FixedRateFactory */
export function useFixedRateFactoryActions() {
  const createMutation = useCreateFixedRateFactory();

  return {
    /** Create FixedRateFactory */
    create: (payload: API.Bond_FixedRate_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create FixedRateInstrument contracts */
export function useCreateFixedRateInstrument() {
  return useContractMutation<API.Bond_FixedRate_Instrument.Payload>(TemplateIds.Bond_FixedRate_Instrument, {
    invalidateQueries: [queryKeys.fixedRateInstrument.all],
  });
}

/** Grouped actions for FixedRateInstrument */
export function useFixedRateInstrumentActions() {
  const createMutation = useCreateFixedRateInstrument();

  return {
    /** Create FixedRateInstrument */
    create: (payload: API.Bond_FixedRate_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create FloatingRateFactory contracts */
export function useCreateFloatingRateFactory() {
  return useContractMutation<API.Bond_FloatingRate_Factory.Payload>(TemplateIds.Bond_FloatingRate_Factory, {
    invalidateQueries: [queryKeys.floatingRateFactory.all],
  });
}

/** Grouped actions for FloatingRateFactory */
export function useFloatingRateFactoryActions() {
  const createMutation = useCreateFloatingRateFactory();

  return {
    /** Create FloatingRateFactory */
    create: (payload: API.Bond_FloatingRate_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create FloatingRateInstrument contracts */
export function useCreateFloatingRateInstrument() {
  return useContractMutation<API.Bond_FloatingRate_Instrument.Payload>(TemplateIds.Bond_FloatingRate_Instrument, {
    invalidateQueries: [queryKeys.floatingRateInstrument.all],
  });
}

/** Grouped actions for FloatingRateInstrument */
export function useFloatingRateInstrumentActions() {
  const createMutation = useCreateFloatingRateInstrument();

  return {
    /** Create FloatingRateInstrument */
    create: (payload: API.Bond_FloatingRate_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create InflationLinkedFactory contracts */
export function useCreateInflationLinkedFactory() {
  return useContractMutation<API.Bond_InflationLinked_Factory.Payload>(TemplateIds.Bond_InflationLinked_Factory, {
    invalidateQueries: [queryKeys.inflationLinkedFactory.all],
  });
}

/** Grouped actions for InflationLinkedFactory */
export function useInflationLinkedFactoryActions() {
  const createMutation = useCreateInflationLinkedFactory();

  return {
    /** Create InflationLinkedFactory */
    create: (payload: API.Bond_InflationLinked_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create InflationLinkedInstrument contracts */
export function useCreateInflationLinkedInstrument() {
  return useContractMutation<API.Bond_InflationLinked_Instrument.Payload>(TemplateIds.Bond_InflationLinked_Instrument, {
    invalidateQueries: [queryKeys.inflationLinkedInstrument.all],
  });
}

/** Grouped actions for InflationLinkedInstrument */
export function useInflationLinkedInstrumentActions() {
  const createMutation = useCreateInflationLinkedInstrument();

  return {
    /** Create InflationLinkedInstrument */
    create: (payload: API.Bond_InflationLinked_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create ZeroCouponFactory contracts */
export function useCreateZeroCouponFactory() {
  return useContractMutation<API.Bond_ZeroCoupon_Factory.Payload>(TemplateIds.Bond_ZeroCoupon_Factory, {
    invalidateQueries: [queryKeys.zeroCouponFactory.all],
  });
}

/** Grouped actions for ZeroCouponFactory */
export function useZeroCouponFactoryActions() {
  const createMutation = useCreateZeroCouponFactory();

  return {
    /** Create ZeroCouponFactory */
    create: (payload: API.Bond_ZeroCoupon_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create ZeroCouponInstrument contracts */
export function useCreateZeroCouponInstrument() {
  return useContractMutation<API.Bond_ZeroCoupon_Instrument.Payload>(TemplateIds.Bond_ZeroCoupon_Instrument, {
    invalidateQueries: [queryKeys.zeroCouponInstrument.all],
  });
}

/** Grouped actions for ZeroCouponInstrument */
export function useZeroCouponInstrumentActions() {
  const createMutation = useCreateZeroCouponInstrument();

  return {
    /** Create ZeroCouponInstrument */
    create: (payload: API.Bond_ZeroCoupon_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create EquityFactory contracts */
export function useCreateEquityFactory() {
  return useContractMutation<API.Equity_Factory.Payload>(TemplateIds.Equity_Factory, {
    invalidateQueries: [queryKeys.equityFactory.all],
  });
}

/** Grouped actions for EquityFactory */
export function useEquityFactoryActions() {
  const createMutation = useCreateEquityFactory();

  return {
    /** Create EquityFactory */
    create: (payload: API.Equity_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create EquityInstrument contracts */
export function useCreateEquityInstrument() {
  return useContractMutation<API.Equity_Instrument.Payload>(TemplateIds.Equity_Instrument, {
    invalidateQueries: [queryKeys.equityInstrument.all],
  });
}

/** Grouped actions for EquityInstrument */
export function useEquityInstrumentActions() {
  const createMutation = useCreateEquityInstrument();

  return {
    /** Create EquityInstrument */
    create: (payload: API.Equity_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create GenericFactory contracts */
export function useCreateGenericFactory() {
  return useContractMutation<API.Generic_Factory.Payload>(TemplateIds.Generic_Factory, {
    invalidateQueries: [queryKeys.genericFactory.all],
  });
}

/** Grouped actions for GenericFactory */
export function useGenericFactoryActions() {
  const createMutation = useCreateGenericFactory();

  return {
    /** Create GenericFactory */
    create: (payload: API.Generic_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create GenericInstrument contracts */
export function useCreateGenericInstrument() {
  return useContractMutation<API.Generic_Instrument.Payload>(TemplateIds.Generic_Instrument, {
    invalidateQueries: [queryKeys.genericInstrument.all],
  });
}

/** Grouped actions for GenericInstrument */
export function useGenericInstrumentActions() {
  const createMutation = useCreateGenericInstrument();

  return {
    /** Create GenericInstrument */
    create: (payload: API.Generic_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create LifecycleRule contracts */
export function useCreateLifecycleRule() {
  return useContractMutation<API.Generic_Lifecycle_Rule.Payload>(TemplateIds.Generic_Lifecycle_Rule, {
    invalidateQueries: [queryKeys.lifecycleRule.all],
  });
}

/** Grouped actions for LifecycleRule */
export function useLifecycleRuleActions() {
  const createMutation = useCreateLifecycleRule();

  return {
    /** Create LifecycleRule */
    create: (payload: API.Generic_Lifecycle_Rule.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create BarrierEuropeanCashFactory contracts */
export function useCreateBarrierEuropeanCashFactory() {
  return useContractMutation<API.Option_BarrierEuropeanCash_Factory.Payload>(TemplateIds.Option_BarrierEuropeanCash_Factory, {
    invalidateQueries: [queryKeys.barrierEuropeanCashFactory.all],
  });
}

/** Grouped actions for BarrierEuropeanCashFactory */
export function useBarrierEuropeanCashFactoryActions() {
  const createMutation = useCreateBarrierEuropeanCashFactory();

  return {
    /** Create BarrierEuropeanCashFactory */
    create: (payload: API.Option_BarrierEuropeanCash_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create BarrierEuropeanCashInstrument contracts */
export function useCreateBarrierEuropeanCashInstrument() {
  return useContractMutation<API.Option_BarrierEuropeanCash_Instrument.Payload>(TemplateIds.Option_BarrierEuropeanCash_Instrument, {
    invalidateQueries: [queryKeys.barrierEuropeanCashInstrument.all],
  });
}

/** Grouped actions for BarrierEuropeanCashInstrument */
export function useBarrierEuropeanCashInstrumentActions() {
  const createMutation = useCreateBarrierEuropeanCashInstrument();

  return {
    /** Create BarrierEuropeanCashInstrument */
    create: (payload: API.Option_BarrierEuropeanCash_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create ElectionFactory contracts */
export function useCreateElectionFactory() {
  return useContractMutation<API.Option_Dividend_Election_Factory.Payload>(TemplateIds.Option_Dividend_Election_Factory, {
    invalidateQueries: [queryKeys.electionFactory.all],
  });
}

/** Grouped actions for ElectionFactory */
export function useElectionFactoryActions() {
  const createMutation = useCreateElectionFactory();

  return {
    /** Create ElectionFactory */
    create: (payload: API.Option_Dividend_Election_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create DividendFactory contracts */
export function useCreateDividendFactory() {
  return useContractMutation<API.Option_Dividend_Factory.Payload>(TemplateIds.Option_Dividend_Factory, {
    invalidateQueries: [queryKeys.dividendFactory.all],
  });
}

/** Grouped actions for DividendFactory */
export function useDividendFactoryActions() {
  const createMutation = useCreateDividendFactory();

  return {
    /** Create DividendFactory */
    create: (payload: API.Option_Dividend_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create DividendInstrument contracts */
export function useCreateDividendInstrument() {
  return useContractMutation<API.Option_Dividend_Instrument.Payload>(TemplateIds.Option_Dividend_Instrument, {
    invalidateQueries: [queryKeys.dividendInstrument.all],
  });
}

/** Grouped actions for DividendInstrument */
export function useDividendInstrumentActions() {
  const createMutation = useCreateDividendInstrument();

  return {
    /** Create DividendInstrument */
    create: (payload: API.Option_Dividend_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create EuropeanCashFactory contracts */
export function useCreateEuropeanCashFactory() {
  return useContractMutation<API.Option_EuropeanCash_Factory.Payload>(TemplateIds.Option_EuropeanCash_Factory, {
    invalidateQueries: [queryKeys.europeanCashFactory.all],
  });
}

/** Grouped actions for EuropeanCashFactory */
export function useEuropeanCashFactoryActions() {
  const createMutation = useCreateEuropeanCashFactory();

  return {
    /** Create EuropeanCashFactory */
    create: (payload: API.Option_EuropeanCash_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create EuropeanCashInstrument contracts */
export function useCreateEuropeanCashInstrument() {
  return useContractMutation<API.Option_EuropeanCash_Instrument.Payload>(TemplateIds.Option_EuropeanCash_Instrument, {
    invalidateQueries: [queryKeys.europeanCashInstrument.all],
  });
}

/** Grouped actions for EuropeanCashInstrument */
export function useEuropeanCashInstrumentActions() {
  const createMutation = useCreateEuropeanCashInstrument();

  return {
    /** Create EuropeanCashInstrument */
    create: (payload: API.Option_EuropeanCash_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create EuropeanPhysicalFactory contracts */
export function useCreateEuropeanPhysicalFactory() {
  return useContractMutation<API.Option_EuropeanPhysical_Factory.Payload>(TemplateIds.Option_EuropeanPhysical_Factory, {
    invalidateQueries: [queryKeys.europeanPhysicalFactory.all],
  });
}

/** Grouped actions for EuropeanPhysicalFactory */
export function useEuropeanPhysicalFactoryActions() {
  const createMutation = useCreateEuropeanPhysicalFactory();

  return {
    /** Create EuropeanPhysicalFactory */
    create: (payload: API.Option_EuropeanPhysical_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create EuropeanPhysicalInstrument contracts */
export function useCreateEuropeanPhysicalInstrument() {
  return useContractMutation<API.Option_EuropeanPhysical_Instrument.Payload>(TemplateIds.Option_EuropeanPhysical_Instrument, {
    invalidateQueries: [queryKeys.europeanPhysicalInstrument.all],
  });
}

/** Grouped actions for EuropeanPhysicalInstrument */
export function useEuropeanPhysicalInstrumentActions() {
  const createMutation = useCreateEuropeanPhysicalInstrument();

  return {
    /** Create EuropeanPhysicalInstrument */
    create: (payload: API.Option_EuropeanPhysical_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create AutoCallableFactory contracts */
export function useCreateAutoCallableFactory() {
  return useContractMutation<API.StructuredProduct_AutoCallable_Factory.Payload>(TemplateIds.StructuredProduct_AutoCallable_Factory, {
    invalidateQueries: [queryKeys.autoCallableFactory.all],
  });
}

/** Grouped actions for AutoCallableFactory */
export function useAutoCallableFactoryActions() {
  const createMutation = useCreateAutoCallableFactory();

  return {
    /** Create AutoCallableFactory */
    create: (payload: API.StructuredProduct_AutoCallable_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create AutoCallableInstrument contracts */
export function useCreateAutoCallableInstrument() {
  return useContractMutation<API.StructuredProduct_AutoCallable_Instrument.Payload>(TemplateIds.StructuredProduct_AutoCallable_Instrument, {
    invalidateQueries: [queryKeys.autoCallableInstrument.all],
  });
}

/** Grouped actions for AutoCallableInstrument */
export function useAutoCallableInstrumentActions() {
  const createMutation = useCreateAutoCallableInstrument();

  return {
    /** Create AutoCallableInstrument */
    create: (payload: API.StructuredProduct_AutoCallable_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create BarrierReverseConvertibleFactory contracts */
export function useCreateBarrierReverseConvertibleFactory() {
  return useContractMutation<API.StructuredProduct_BarrierReverseConvertible_Factory.Payload>(TemplateIds.StructuredProduct_BarrierReverseConvertible_Factory, {
    invalidateQueries: [queryKeys.barrierReverseConvertibleFactory.all],
  });
}

/** Grouped actions for BarrierReverseConvertibleFactory */
export function useBarrierReverseConvertibleFactoryActions() {
  const createMutation = useCreateBarrierReverseConvertibleFactory();

  return {
    /** Create BarrierReverseConvertibleFactory */
    create: (payload: API.StructuredProduct_BarrierReverseConvertible_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create BarrierReverseConvertibleInstrument contracts */
export function useCreateBarrierReverseConvertibleInstrument() {
  return useContractMutation<API.StructuredProduct_BarrierReverseConvertible_Instrument.Payload>(TemplateIds.StructuredProduct_BarrierReverseConvertible_Instrument, {
    invalidateQueries: [queryKeys.barrierReverseConvertibleInstrument.all],
  });
}

/** Grouped actions for BarrierReverseConvertibleInstrument */
export function useBarrierReverseConvertibleInstrumentActions() {
  const createMutation = useCreateBarrierReverseConvertibleInstrument();

  return {
    /** Create BarrierReverseConvertibleInstrument */
    create: (payload: API.StructuredProduct_BarrierReverseConvertible_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create DistributionRule contracts */
export function useCreateDistributionRule() {
  return useContractMutation<API.Swap_Asset_DistributionRule.Payload>(TemplateIds.Swap_Asset_DistributionRule, {
    invalidateQueries: [queryKeys.distributionRule.all],
  });
}

/** Grouped actions for DistributionRule */
export function useDistributionRuleActions() {
  const createMutation = useCreateDistributionRule();

  return {
    /** Create DistributionRule */
    create: (payload: API.Swap_Asset_DistributionRule.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create AssetFactory contracts */
export function useCreateAssetFactory() {
  return useContractMutation<API.Swap_Asset_Factory.Payload>(TemplateIds.Swap_Asset_Factory, {
    invalidateQueries: [queryKeys.assetFactory.all],
  });
}

/** Grouped actions for AssetFactory */
export function useAssetFactoryActions() {
  const createMutation = useCreateAssetFactory();

  return {
    /** Create AssetFactory */
    create: (payload: API.Swap_Asset_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create AssetInstrument contracts */
export function useCreateAssetInstrument() {
  return useContractMutation<API.Swap_Asset_Instrument.Payload>(TemplateIds.Swap_Asset_Instrument, {
    invalidateQueries: [queryKeys.assetInstrument.all],
  });
}

/** Grouped actions for AssetInstrument */
export function useAssetInstrumentActions() {
  const createMutation = useCreateAssetInstrument();

  return {
    /** Create AssetInstrument */
    create: (payload: API.Swap_Asset_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create CreditDefaultFactory contracts */
export function useCreateCreditDefaultFactory() {
  return useContractMutation<API.Swap_CreditDefault_Factory.Payload>(TemplateIds.Swap_CreditDefault_Factory, {
    invalidateQueries: [queryKeys.creditDefaultFactory.all],
  });
}

/** Grouped actions for CreditDefaultFactory */
export function useCreditDefaultFactoryActions() {
  const createMutation = useCreateCreditDefaultFactory();

  return {
    /** Create CreditDefaultFactory */
    create: (payload: API.Swap_CreditDefault_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create CreditDefaultInstrument contracts */
export function useCreateCreditDefaultInstrument() {
  return useContractMutation<API.Swap_CreditDefault_Instrument.Payload>(TemplateIds.Swap_CreditDefault_Instrument, {
    invalidateQueries: [queryKeys.creditDefaultInstrument.all],
  });
}

/** Grouped actions for CreditDefaultInstrument */
export function useCreditDefaultInstrumentActions() {
  const createMutation = useCreateCreditDefaultInstrument();

  return {
    /** Create CreditDefaultInstrument */
    create: (payload: API.Swap_CreditDefault_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create CurrencyFactory contracts */
export function useCreateCurrencyFactory() {
  return useContractMutation<API.Swap_Currency_Factory.Payload>(TemplateIds.Swap_Currency_Factory, {
    invalidateQueries: [queryKeys.currencyFactory.all],
  });
}

/** Grouped actions for CurrencyFactory */
export function useCurrencyFactoryActions() {
  const createMutation = useCreateCurrencyFactory();

  return {
    /** Create CurrencyFactory */
    create: (payload: API.Swap_Currency_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create CurrencyInstrument contracts */
export function useCreateCurrencyInstrument() {
  return useContractMutation<API.Swap_Currency_Instrument.Payload>(TemplateIds.Swap_Currency_Instrument, {
    invalidateQueries: [queryKeys.currencyInstrument.all],
  });
}

/** Grouped actions for CurrencyInstrument */
export function useCurrencyInstrumentActions() {
  const createMutation = useCreateCurrencyInstrument();

  return {
    /** Create CurrencyInstrument */
    create: (payload: API.Swap_Currency_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create ForeignExchangeFactory contracts */
export function useCreateForeignExchangeFactory() {
  return useContractMutation<API.Swap_ForeignExchange_Factory.Payload>(TemplateIds.Swap_ForeignExchange_Factory, {
    invalidateQueries: [queryKeys.foreignExchangeFactory.all],
  });
}

/** Grouped actions for ForeignExchangeFactory */
export function useForeignExchangeFactoryActions() {
  const createMutation = useCreateForeignExchangeFactory();

  return {
    /** Create ForeignExchangeFactory */
    create: (payload: API.Swap_ForeignExchange_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create ForeignExchangeInstrument contracts */
export function useCreateForeignExchangeInstrument() {
  return useContractMutation<API.Swap_ForeignExchange_Instrument.Payload>(TemplateIds.Swap_ForeignExchange_Instrument, {
    invalidateQueries: [queryKeys.foreignExchangeInstrument.all],
  });
}

/** Grouped actions for ForeignExchangeInstrument */
export function useForeignExchangeInstrumentActions() {
  const createMutation = useCreateForeignExchangeInstrument();

  return {
    /** Create ForeignExchangeInstrument */
    create: (payload: API.Swap_ForeignExchange_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create FpmlFactory contracts */
export function useCreateFpmlFactory() {
  return useContractMutation<API.Swap_Fpml_Factory.Payload>(TemplateIds.Swap_Fpml_Factory, {
    invalidateQueries: [queryKeys.fpmlFactory.all],
  });
}

/** Grouped actions for FpmlFactory */
export function useFpmlFactoryActions() {
  const createMutation = useCreateFpmlFactory();

  return {
    /** Create FpmlFactory */
    create: (payload: API.Swap_Fpml_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create FpmlInstrument contracts */
export function useCreateFpmlInstrument() {
  return useContractMutation<API.Swap_Fpml_Instrument.Payload>(TemplateIds.Swap_Fpml_Instrument, {
    invalidateQueries: [queryKeys.fpmlInstrument.all],
  });
}

/** Grouped actions for FpmlInstrument */
export function useFpmlInstrumentActions() {
  const createMutation = useCreateFpmlInstrument();

  return {
    /** Create FpmlInstrument */
    create: (payload: API.Swap_Fpml_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create InterestRateFactory contracts */
export function useCreateInterestRateFactory() {
  return useContractMutation<API.Swap_InterestRate_Factory.Payload>(TemplateIds.Swap_InterestRate_Factory, {
    invalidateQueries: [queryKeys.interestRateFactory.all],
  });
}

/** Grouped actions for InterestRateFactory */
export function useInterestRateFactoryActions() {
  const createMutation = useCreateInterestRateFactory();

  return {
    /** Create InterestRateFactory */
    create: (payload: API.Swap_InterestRate_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create InterestRateInstrument contracts */
export function useCreateInterestRateInstrument() {
  return useContractMutation<API.Swap_InterestRate_Instrument.Payload>(TemplateIds.Swap_InterestRate_Instrument, {
    invalidateQueries: [queryKeys.interestRateInstrument.all],
  });
}

/** Grouped actions for InterestRateInstrument */
export function useInterestRateInstrumentActions() {
  const createMutation = useCreateInterestRateInstrument();

  return {
    /** Create InterestRateInstrument */
    create: (payload: API.Swap_InterestRate_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create TokenFactory contracts */
export function useCreateTokenFactory() {
  return useContractMutation<API.Token_Factory.Payload>(TemplateIds.Token_Factory, {
    invalidateQueries: [queryKeys.tokenFactory.all],
  });
}

/** Grouped actions for TokenFactory */
export function useTokenFactoryActions() {
  const createMutation = useCreateTokenFactory();

  return {
    /** Create TokenFactory */
    create: (payload: API.Token_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create TokenInstrument contracts */
export function useCreateTokenInstrument() {
  return useContractMutation<API.Token_Instrument.Payload>(TemplateIds.Token_Instrument, {
    invalidateQueries: [queryKeys.tokenInstrument.all],
  });
}

/** Grouped actions for TokenInstrument */
export function useTokenInstrumentActions() {
  const createMutation = useCreateTokenInstrument();

  return {
    /** Create TokenInstrument */
    create: (payload: API.Token_Instrument.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create Reference contracts */
export function useCreateReference() {
  return useContractMutation<API.Account_Account_Reference.Payload>(TemplateIds.Account_Account_Reference, {
    invalidateQueries: [queryKeys.reference.all],
  });
}

/** Exercise SetCid on Reference */
export function useSetCidReference() {
  return useChoiceMutation<Parameters<typeof API.Account_Account_Reference.setCid>[1], CommandResult<ReturnType<typeof API.Account_Account_Reference.setCid>>>(
    TemplateIds.Account_Account_Reference,
    'SetCid',
    { invalidateQueries: [queryKeys.reference.all] }
  );
}

/** Exercise SetObservers on Reference */
export function useSetObserversReference() {
  return useChoiceMutation<Parameters<typeof API.Account_Account_Reference.setObservers>[1], CommandResult<ReturnType<typeof API.Account_Account_Reference.setObservers>>>(
    TemplateIds.Account_Account_Reference,
    'SetObservers',
    { invalidateQueries: [queryKeys.reference.all] }
  );
}

/** Exercise GetCid on Reference */
export function useGetCidReference() {
  return useChoiceMutation<Parameters<typeof API.Account_Account_Reference.getCid>[1], CommandResult<ReturnType<typeof API.Account_Account_Reference.getCid>>>(
    TemplateIds.Account_Account_Reference,
    'GetCid',
    { invalidateQueries: [queryKeys.reference.all] }
  );
}

/** Grouped actions for Reference */
export function useReferenceActions() {
  const createMutation = useCreateReference();
  const setCidMutation = useSetCidReference();
  const setObserversMutation = useSetObserversReference();
  const getCidMutation = useGetCidReference();

  return {
    /** Create Reference */
    create: (payload: API.Account_Account_Reference.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    /** SetCid */
    setCid: (contractId: string, args: Parameters<typeof API.Account_Account_Reference.setCid>[1]) =>
      setCidMutation.mutateAsync({ contractId, args }),
    isSetCiding: setCidMutation.isPending,
    /** SetObservers */
    setObservers: (contractId: string, args: Parameters<typeof API.Account_Account_Reference.setObservers>[1]) =>
      setObserversMutation.mutateAsync({ contractId, args }),
    isSetObserversing: setObserversMutation.isPending,
    /** GetCid */
    getCid: (contractId: string, args: Parameters<typeof API.Account_Account_Reference.getCid>[1]) =>
      getCidMutation.mutateAsync({ contractId, args }),
    isGetCiding: getCidMutation.isPending,
    error: createMutation.error || setCidMutation.error || setObserversMutation.error || getCidMutation.error,
  };
}

/** Create FactoryReference contracts */
export function useCreateFactoryReference() {
  return useContractMutation<API.Holding_Factory_Reference.Payload>(TemplateIds.Holding_Factory_Reference, {
    invalidateQueries: [queryKeys.factoryReference.all],
  });
}

/** Exercise SetCid on FactoryReference */
export function useSetCidFactoryReference() {
  return useChoiceMutation<Parameters<typeof API.Holding_Factory_Reference.setCid>[1], CommandResult<ReturnType<typeof API.Holding_Factory_Reference.setCid>>>(
    TemplateIds.Holding_Factory_Reference,
    'SetCid',
    { invalidateQueries: [queryKeys.factoryReference.all] }
  );
}

/** Exercise SetObservers on FactoryReference */
export function useSetObserversFactoryReference() {
  return useChoiceMutation<Parameters<typeof API.Holding_Factory_Reference.setObservers>[1], CommandResult<ReturnType<typeof API.Holding_Factory_Reference.setObservers>>>(
    TemplateIds.Holding_Factory_Reference,
    'SetObservers',
    { invalidateQueries: [queryKeys.factoryReference.all] }
  );
}

/** Exercise GetCid on FactoryReference */
export function useGetCidFactoryReference() {
  return useChoiceMutation<Parameters<typeof API.Holding_Factory_Reference.getCid>[1], CommandResult<ReturnType<typeof API.Holding_Factory_Reference.getCid>>>(
    TemplateIds.Holding_Factory_Reference,
    'GetCid',
    { invalidateQueries: [queryKeys.factoryReference.all] }
  );
}

/** Grouped actions for FactoryReference */
export function useFactoryReferenceActions() {
  const createMutation = useCreateFactoryReference();
  const setCidMutation = useSetCidFactoryReference();
  const setObserversMutation = useSetObserversFactoryReference();
  const getCidMutation = useGetCidFactoryReference();

  return {
    /** Create FactoryReference */
    create: (payload: API.Holding_Factory_Reference.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    /** SetCid */
    setCid: (contractId: string, args: Parameters<typeof API.Holding_Factory_Reference.setCid>[1]) =>
      setCidMutation.mutateAsync({ contractId, args }),
    isSetCiding: setCidMutation.isPending,
    /** SetObservers */
    setObservers: (contractId: string, args: Parameters<typeof API.Holding_Factory_Reference.setObservers>[1]) =>
      setObserversMutation.mutateAsync({ contractId, args }),
    isSetObserversing: setObserversMutation.isPending,
    /** GetCid */
    getCid: (contractId: string, args: Parameters<typeof API.Holding_Factory_Reference.getCid>[1]) =>
      getCidMutation.mutateAsync({ contractId, args }),
    isGetCiding: getCidMutation.isPending,
    error: createMutation.error || setCidMutation.error || setObserversMutation.error || getCidMutation.error,
  };
}

/** Create InstrumentReference contracts */
export function useCreateInstrumentReference() {
  return useContractMutation<API.Base_Instrument_Reference.Payload>(TemplateIds.Base_Instrument_Reference, {
    invalidateQueries: [queryKeys.instrumentReference.all],
  });
}

/** Exercise SetCid on InstrumentReference */
export function useSetCidInstrumentReference() {
  return useChoiceMutation<Parameters<typeof API.Base_Instrument_Reference.setCid>[1], CommandResult<ReturnType<typeof API.Base_Instrument_Reference.setCid>>>(
    TemplateIds.Base_Instrument_Reference,
    'SetCid',
    { invalidateQueries: [queryKeys.instrumentReference.all] }
  );
}

/** Exercise SetObservers on InstrumentReference */
export function useSetObserversInstrumentReference() {
  return useChoiceMutation<Parameters<typeof API.Base_Instrument_Reference.setObservers>[1], CommandResult<ReturnType<typeof API.Base_Instrument_Reference.setObservers>>>(
    TemplateIds.Base_Instrument_Reference,
    'SetObservers',
    { invalidateQueries: [queryKeys.instrumentReference.all] }
  );
}

/** Exercise GetCid on InstrumentReference */
export function useGetCidInstrumentReference() {
  return useChoiceMutation<Parameters<typeof API.Base_Instrument_Reference.getCid>[1], CommandResult<ReturnType<typeof API.Base_Instrument_Reference.getCid>>>(
    TemplateIds.Base_Instrument_Reference,
    'GetCid',
    { invalidateQueries: [queryKeys.instrumentReference.all] }
  );
}

/** Grouped actions for InstrumentReference */
export function useInstrumentReferenceActions() {
  const createMutation = useCreateInstrumentReference();
  const setCidMutation = useSetCidInstrumentReference();
  const setObserversMutation = useSetObserversInstrumentReference();
  const getCidMutation = useGetCidInstrumentReference();

  return {
    /** Create InstrumentReference */
    create: (payload: API.Base_Instrument_Reference.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    /** SetCid */
    setCid: (contractId: string, args: Parameters<typeof API.Base_Instrument_Reference.setCid>[1]) =>
      setCidMutation.mutateAsync({ contractId, args }),
    isSetCiding: setCidMutation.isPending,
    /** SetObservers */
    setObservers: (contractId: string, args: Parameters<typeof API.Base_Instrument_Reference.setObservers>[1]) =>
      setObserversMutation.mutateAsync({ contractId, args }),
    isSetObserversing: setObserversMutation.isPending,
    /** GetCid */
    getCid: (contractId: string, args: Parameters<typeof API.Base_Instrument_Reference.getCid>[1]) =>
      getCidMutation.mutateAsync({ contractId, args }),
    isGetCiding: getCidMutation.isPending,
    error: createMutation.error || setCidMutation.error || setObserversMutation.error || getCidMutation.error,
  };
}

/** Create Effect contracts */
export function useCreateEffect() {
  return useContractMutation<API.Lifecycle_Effect.Payload>(TemplateIds.Lifecycle_Effect, {
    invalidateQueries: [queryKeys.effect.all],
  });
}

/** Grouped actions for Effect */
export function useEffectActions() {
  const createMutation = useCreateEffect();

  return {
    /** Create Effect */
    create: (payload: API.Lifecycle_Effect.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create LifecycleElectionFactory contracts */
export function useCreateLifecycleElectionFactory() {
  return useContractMutation<API.Lifecycle_Election_Factory.Payload>(TemplateIds.Lifecycle_Election_Factory, {
    invalidateQueries: [queryKeys.lifecycleElectionFactory.all],
  });
}

/** Grouped actions for LifecycleElectionFactory */
export function useLifecycleElectionFactoryActions() {
  const createMutation = useCreateLifecycleElectionFactory();

  return {
    /** Create LifecycleElectionFactory */
    create: (payload: API.Lifecycle_Election_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create Election contracts */
export function useCreateElection() {
  return useContractMutation<API.Lifecycle_Election.Payload>(TemplateIds.Lifecycle_Election, {
    invalidateQueries: [queryKeys.election.all],
  });
}

/** Grouped actions for Election */
export function useElectionActions() {
  const createMutation = useCreateElection();

  return {
    /** Create Election */
    create: (payload: API.Lifecycle_Election.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create ElectionEffect contracts */
export function useCreateElectionEffect() {
  return useContractMutation<API.Lifecycle_ElectionEffect.Payload>(TemplateIds.Lifecycle_ElectionEffect, {
    invalidateQueries: [queryKeys.electionEffect.all],
  });
}

/** Grouped actions for ElectionEffect */
export function useElectionEffectActions() {
  const createMutation = useCreateElectionEffect();

  return {
    /** Create ElectionEffect */
    create: (payload: API.Lifecycle_ElectionEffect.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create Event contracts */
export function useCreateEvent() {
  return useContractMutation<API.Lifecycle_Distribution_Event.Payload>(TemplateIds.Lifecycle_Distribution_Event, {
    invalidateQueries: [queryKeys.event.all],
  });
}

/** Grouped actions for Event */
export function useEventActions() {
  const createMutation = useCreateEvent();

  return {
    /** Create Event */
    create: (payload: API.Lifecycle_Distribution_Event.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create ReplacementEvent contracts */
export function useCreateReplacementEvent() {
  return useContractMutation<API.Lifecycle_Replacement_Event.Payload>(TemplateIds.Lifecycle_Replacement_Event, {
    invalidateQueries: [queryKeys.replacementEvent.all],
  });
}

/** Grouped actions for ReplacementEvent */
export function useReplacementEventActions() {
  const createMutation = useCreateReplacementEvent();

  return {
    /** Create ReplacementEvent */
    create: (payload: API.Lifecycle_Replacement_Event.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create ClaimRule contracts */
export function useCreateClaimRule() {
  return useContractMutation<API.Lifecycle_Claim_Rule.Payload>(TemplateIds.Lifecycle_Claim_Rule, {
    invalidateQueries: [queryKeys.claimRule.all],
  });
}

/** Grouped actions for ClaimRule */
export function useClaimRuleActions() {
  const createMutation = useCreateClaimRule();

  return {
    /** Create ClaimRule */
    create: (payload: API.Lifecycle_Claim_Rule.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create LifecycleDistributionRule contracts */
export function useCreateLifecycleDistributionRule() {
  return useContractMutation<API.Lifecycle_Distribution_Rule.Payload>(TemplateIds.Lifecycle_Distribution_Rule, {
    invalidateQueries: [queryKeys.lifecycleDistributionRule.all],
  });
}

/** Grouped actions for LifecycleDistributionRule */
export function useLifecycleDistributionRuleActions() {
  const createMutation = useCreateLifecycleDistributionRule();

  return {
    /** Create LifecycleDistributionRule */
    create: (payload: API.Lifecycle_Distribution_Rule.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create ReplacementRule contracts */
export function useCreateReplacementRule() {
  return useContractMutation<API.Lifecycle_Replacement_Rule.Payload>(TemplateIds.Lifecycle_Replacement_Rule, {
    invalidateQueries: [queryKeys.replacementRule.all],
  });
}

/** Grouped actions for ReplacementRule */
export function useReplacementRuleActions() {
  const createMutation = useCreateReplacementRule();

  return {
    /** Create ReplacementRule */
    create: (payload: API.Lifecycle_Replacement_Rule.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create Batch contracts */
export function useCreateBatch() {
  return useContractMutation<API.Settlement_Batch.Payload>(TemplateIds.Settlement_Batch, {
    invalidateQueries: [queryKeys.batch.all],
  });
}

/** Grouped actions for Batch */
export function useBatchActions() {
  const createMutation = useCreateBatch();

  return {
    /** Create Batch */
    create: (payload: API.Settlement_Batch.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create SettlementFactory contracts */
export function useCreateSettlementFactory() {
  return useContractMutation<API.Settlement_Factory.Payload>(TemplateIds.Settlement_Factory, {
    invalidateQueries: [queryKeys.settlementFactory.all],
  });
}

/** Grouped actions for SettlementFactory */
export function useSettlementFactoryActions() {
  const createMutation = useCreateSettlementFactory();

  return {
    /** Create SettlementFactory */
    create: (payload: API.Settlement_Factory.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create Instruction contracts */
export function useCreateInstruction() {
  return useContractMutation<API.Settlement_Instruction.Payload>(TemplateIds.Settlement_Instruction, {
    invalidateQueries: [queryKeys.instruction.all],
  });
}

/** Grouped actions for Instruction */
export function useInstructionActions() {
  const createMutation = useCreateInstruction();

  return {
    /** Create Instruction */
    create: (payload: API.Settlement_Instruction.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create IntermediatedStatic contracts */
export function useCreateIntermediatedStatic() {
  return useContractMutation<API.Settlement_RouteProvider_IntermediatedStatic.Payload>(TemplateIds.Settlement_RouteProvider_IntermediatedStatic, {
    invalidateQueries: [queryKeys.intermediatedStatic.all],
  });
}

/** Grouped actions for IntermediatedStatic */
export function useIntermediatedStaticActions() {
  const createMutation = useCreateIntermediatedStatic();

  return {
    /** Create IntermediatedStatic */
    create: (payload: API.Settlement_RouteProvider_IntermediatedStatic.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create SingleCustodian contracts */
export function useCreateSingleCustodian() {
  return useContractMutation<API.Settlement_RouteProvider_SingleCustodian.Payload>(TemplateIds.Settlement_RouteProvider_SingleCustodian, {
    invalidateQueries: [queryKeys.singleCustodian.all],
  });
}

/** Grouped actions for SingleCustodian */
export function useSingleCustodianActions() {
  const createMutation = useCreateSingleCustodian();

  return {
    /** Create SingleCustodian */
    create: (payload: API.Settlement_RouteProvider_SingleCustodian.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    error: createMutation.error,
  };
}

/** Create LunarDollar contracts */
export function useCreateLunarDollar() {
  return useContractMutation<API.LunarDollar.Payload>(TemplateIds.LunarDollar, {
    invalidateQueries: [queryKeys.lunarDollar.all],
  });
}

/** Exercise Mint on LunarDollar */
export function useMintLunarDollar() {
  return useChoiceMutation<Parameters<typeof API.LunarDollar.mint>[1], CommandResult<ReturnType<typeof API.LunarDollar.mint>>>(
    TemplateIds.LunarDollar,
    'Mint',
    { invalidateQueries: [queryKeys.lunarDollar.all] }
  );
}

/** Exercise Merge on LunarDollar */
export function useMergeLunarDollar() {
  return useChoiceMutation<Parameters<typeof API.LunarDollar.merge>[1], CommandResult<ReturnType<typeof API.LunarDollar.merge>>>(
    TemplateIds.LunarDollar,
    'Merge',
    { invalidateQueries: [queryKeys.lunarDollar.all] }
  );
}

/** Grouped actions for LunarDollar */
export function useLunarDollarActions() {
  const createMutation = useCreateLunarDollar();
  const mintMutation = useMintLunarDollar();
  const mergeMutation = useMergeLunarDollar();

  return {
    /** Create LunarDollar */
    create: (payload: API.LunarDollar.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    /** Mint */
    mint: (contractId: string, args: Parameters<typeof API.LunarDollar.mint>[1]) =>
      mintMutation.mutateAsync({ contractId, args }),
    isMinting: mintMutation.isPending,
    /** Merge */
    merge: (contractId: string, args: Parameters<typeof API.LunarDollar.merge>[1]) =>
      mergeMutation.mutateAsync({ contractId, args }),
    isMerging: mergeMutation.isPending,
    error: createMutation.error || mintMutation.error || mergeMutation.error,
  };
}

/** Create PaymentReceiver contracts */
export function useCreatePaymentReceiver() {
  return useContractMutation<API.PaymentReceiver.Payload>(TemplateIds.PaymentReceiver, {
    invalidateQueries: [queryKeys.paymentReceiver.all],
  });
}

/** Exercise Pay on PaymentReceiver */
export function usePayPaymentReceiver() {
  return useChoiceMutation<Parameters<typeof API.PaymentReceiver.pay>[1], CommandResult<ReturnType<typeof API.PaymentReceiver.pay>>>(
    TemplateIds.PaymentReceiver,
    'Pay',
    { invalidateQueries: [queryKeys.paymentReceiver.all] }
  );
}

/** Grouped actions for PaymentReceiver */
export function usePaymentReceiverActions() {
  const createMutation = useCreatePaymentReceiver();
  const payMutation = usePayPaymentReceiver();

  return {
    /** Create PaymentReceiver */
    create: (payload: API.PaymentReceiver.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    /** Pay */
    pay: (contractId: string, args: Parameters<typeof API.PaymentReceiver.pay>[1]) =>
      payMutation.mutateAsync({ contractId, args }),
    isPaying: payMutation.isPending,
    error: createMutation.error || payMutation.error,
  };
}

/** Create AccessGrant contracts */
export function useCreateAccessGrant() {
  return useContractMutation<API.PaymentReceiver_AccessGrant.Payload>(TemplateIds.PaymentReceiver_AccessGrant, {
    invalidateQueries: [queryKeys.accessGrant.all],
  });
}

/** Exercise ConsumeAccess on AccessGrant */
export function useConsumeAccessAccessGrant() {
  return useChoiceMutation<Parameters<typeof API.PaymentReceiver_AccessGrant.consumeAccess>[1], CommandResult<ReturnType<typeof API.PaymentReceiver_AccessGrant.consumeAccess>>>(
    TemplateIds.PaymentReceiver_AccessGrant,
    'ConsumeAccess',
    { invalidateQueries: [queryKeys.accessGrant.all] }
  );
}

/** Grouped actions for AccessGrant */
export function useAccessGrantActions() {
  const createMutation = useCreateAccessGrant();
  const consumeAccessMutation = useConsumeAccessAccessGrant();

  return {
    /** Create AccessGrant */
    create: (payload: API.PaymentReceiver_AccessGrant.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    /** ConsumeAccess */
    consumeAccess: (contractId: string, args: Parameters<typeof API.PaymentReceiver_AccessGrant.consumeAccess>[1]) =>
      consumeAccessMutation.mutateAsync({ contractId, args }),
    isConsumeAccessing: consumeAccessMutation.isPending,
    error: createMutation.error || consumeAccessMutation.error,
  };
}

/** Create TransferRequest contracts */
export function useCreateTransferRequest() {
  return useContractMutation<API.TransferRequest.Payload>(TemplateIds.TransferRequest, {
    invalidateQueries: [queryKeys.transferRequest.all],
  });
}

/** Exercise Accept on TransferRequest */
export function useAcceptTransferRequest() {
  return useChoiceMutation<Parameters<typeof API.TransferRequest.accept>[1], CommandResult<ReturnType<typeof API.TransferRequest.accept>>>(
    TemplateIds.TransferRequest,
    'Accept',
    { invalidateQueries: [queryKeys.transferRequest.all] }
  );
}

/** Exercise Decline on TransferRequest */
export function useDeclineTransferRequest() {
  return useChoiceMutation<Parameters<typeof API.TransferRequest.decline>[1], CommandResult<ReturnType<typeof API.TransferRequest.decline>>>(
    TemplateIds.TransferRequest,
    'Decline',
    { invalidateQueries: [queryKeys.transferRequest.all] }
  );
}

/** Exercise Withdraw on TransferRequest */
export function useWithdrawTransferRequest() {
  return useChoiceMutation<Parameters<typeof API.TransferRequest.withdraw>[1], CommandResult<ReturnType<typeof API.TransferRequest.withdraw>>>(
    TemplateIds.TransferRequest,
    'Withdraw',
    { invalidateQueries: [queryKeys.transferRequest.all] }
  );
}

/** Grouped actions for TransferRequest */
export function useTransferRequestActions() {
  const createMutation = useCreateTransferRequest();
  const acceptMutation = useAcceptTransferRequest();
  const declineMutation = useDeclineTransferRequest();
  const withdrawMutation = useWithdrawTransferRequest();

  return {
    /** Create TransferRequest */
    create: (payload: API.TransferRequest.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    /** Accept */
    accept: (contractId: string, args: Parameters<typeof API.TransferRequest.accept>[1]) =>
      acceptMutation.mutateAsync({ contractId, args }),
    isAccepting: acceptMutation.isPending,
    /** Decline */
    decline: (contractId: string, args: Parameters<typeof API.TransferRequest.decline>[1]) =>
      declineMutation.mutateAsync({ contractId, args }),
    isDeclining: declineMutation.isPending,
    /** Withdraw */
    withdraw: (contractId: string, args: Parameters<typeof API.TransferRequest.withdraw>[1]) =>
      withdrawMutation.mutateAsync({ contractId, args }),
    isWithdrawing: withdrawMutation.isPending,
    error: createMutation.error || acceptMutation.error || declineMutation.error || withdrawMutation.error,
  };
}

/** Create Request contracts */
export function useCreateRequest() {
  return useContractMutation<API.Workflow_CreateAccount_Request.Payload>(TemplateIds.Workflow_CreateAccount_Request, {
    invalidateQueries: [queryKeys.request.all],
  });
}

/** Exercise Accept on Request */
export function useAcceptRequest() {
  return useChoiceMutation<Parameters<typeof API.Workflow_CreateAccount_Request.accept>[1], CommandResult<ReturnType<typeof API.Workflow_CreateAccount_Request.accept>>>(
    TemplateIds.Workflow_CreateAccount_Request,
    'Accept',
    { invalidateQueries: [queryKeys.request.all] }
  );
}

/** Exercise Decline on Request */
export function useDeclineRequest() {
  return useChoiceMutation<Parameters<typeof API.Workflow_CreateAccount_Request.decline>[1], CommandResult<ReturnType<typeof API.Workflow_CreateAccount_Request.decline>>>(
    TemplateIds.Workflow_CreateAccount_Request,
    'Decline',
    { invalidateQueries: [queryKeys.request.all] }
  );
}

/** Exercise Withdraw on Request */
export function useWithdrawRequest() {
  return useChoiceMutation<Parameters<typeof API.Workflow_CreateAccount_Request.withdraw>[1], CommandResult<ReturnType<typeof API.Workflow_CreateAccount_Request.withdraw>>>(
    TemplateIds.Workflow_CreateAccount_Request,
    'Withdraw',
    { invalidateQueries: [queryKeys.request.all] }
  );
}

/** Grouped actions for Request */
export function useRequestActions() {
  const createMutation = useCreateRequest();
  const acceptMutation = useAcceptRequest();
  const declineMutation = useDeclineRequest();
  const withdrawMutation = useWithdrawRequest();

  return {
    /** Create Request */
    create: (payload: API.Workflow_CreateAccount_Request.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    /** Accept */
    accept: (contractId: string, args: Parameters<typeof API.Workflow_CreateAccount_Request.accept>[1]) =>
      acceptMutation.mutateAsync({ contractId, args }),
    isAccepting: acceptMutation.isPending,
    /** Decline */
    decline: (contractId: string, args: Parameters<typeof API.Workflow_CreateAccount_Request.decline>[1]) =>
      declineMutation.mutateAsync({ contractId, args }),
    isDeclining: declineMutation.isPending,
    /** Withdraw */
    withdraw: (contractId: string, args: Parameters<typeof API.Workflow_CreateAccount_Request.withdraw>[1]) =>
      withdrawMutation.mutateAsync({ contractId, args }),
    isWithdrawing: withdrawMutation.isPending,
    error: createMutation.error || acceptMutation.error || declineMutation.error || withdrawMutation.error,
  };
}

/** Create CreditAccountRequest contracts */
export function useCreateCreditAccountRequest() {
  return useContractMutation<API.Workflow_CreditAccount_Request.Payload>(TemplateIds.Workflow_CreditAccount_Request, {
    invalidateQueries: [queryKeys.creditAccountRequest.all],
  });
}

/** Exercise Accept on CreditAccountRequest */
export function useAcceptCreditAccountRequest() {
  return useChoiceMutation<Parameters<typeof API.Workflow_CreditAccount_Request.accept>[1], CommandResult<ReturnType<typeof API.Workflow_CreditAccount_Request.accept>>>(
    TemplateIds.Workflow_CreditAccount_Request,
    'Accept',
    { invalidateQueries: [queryKeys.creditAccountRequest.all] }
  );
}

/** Exercise Decline on CreditAccountRequest */
export function useDeclineCreditAccountRequest() {
  return useChoiceMutation<Parameters<typeof API.Workflow_CreditAccount_Request.decline>[1], CommandResult<ReturnType<typeof API.Workflow_CreditAccount_Request.decline>>>(
    TemplateIds.Workflow_CreditAccount_Request,
    'Decline',
    { invalidateQueries: [queryKeys.creditAccountRequest.all] }
  );
}

/** Exercise Withdraw on CreditAccountRequest */
export function useWithdrawCreditAccountRequest() {
  return useChoiceMutation<Parameters<typeof API.Workflow_CreditAccount_Request.withdraw>[1], CommandResult<ReturnType<typeof API.Workflow_CreditAccount_Request.withdraw>>>(
    TemplateIds.Workflow_CreditAccount_Request,
    'Withdraw',
    { invalidateQueries: [queryKeys.creditAccountRequest.all] }
  );
}

/** Grouped actions for CreditAccountRequest */
export function useCreditAccountRequestActions() {
  const createMutation = useCreateCreditAccountRequest();
  const acceptMutation = useAcceptCreditAccountRequest();
  const declineMutation = useDeclineCreditAccountRequest();
  const withdrawMutation = useWithdrawCreditAccountRequest();

  return {
    /** Create CreditAccountRequest */
    create: (payload: API.Workflow_CreditAccount_Request.Payload) => createMutation.mutateAsync(payload),
    isCreating: createMutation.isPending,
    /** Accept */
    accept: (contractId: string, args: Parameters<typeof API.Workflow_CreditAccount_Request.accept>[1]) =>
      acceptMutation.mutateAsync({ contractId, args }),
    isAccepting: acceptMutation.isPending,
    /** Decline */
    decline: (contractId: string, args: Parameters<typeof API.Workflow_CreditAccount_Request.decline>[1]) =>
      declineMutation.mutateAsync({ contractId, args }),
    isDeclining: declineMutation.isPending,
    /** Withdraw */
    withdraw: (contractId: string, args: Parameters<typeof API.Workflow_CreditAccount_Request.withdraw>[1]) =>
      withdrawMutation.mutateAsync({ contractId, args }),
    isWithdrawing: withdrawMutation.isPending,
    error: createMutation.error || acceptMutation.error || declineMutation.error || withdrawMutation.error,
  };
}

