// react/hooks/queries.ts
// Generated typed query hooks for ALL contract types
// DO NOT EDIT - Generated by generate-canton-react.ts

import { useContractQuery } from './core';
import type { UseQueryResult } from '@tanstack/react-query';
import { TemplateIds } from '../../lunar-dollar-api';
import type { Contract } from '../../core';
import type * as API from '../../lunar-dollar-api';

// ═══════════════════════════════════════════════════════════════
// TYPED QUERY HOOKS
// ═══════════════════════════════════════════════════════════════

/** Query Account_Account_Factory contracts with full type safety. */
export function useFactories(
  filter?: Partial<API.Account_Account_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Account_Account_Factory.Payload>[]> {
  return useContractQuery<API.Account_Account_Factory.Payload>(TemplateIds.Account_Account_Factory, filter, options);
}

/** Query Account contracts with full type safety. */
export function useAccounts(
  filter?: Partial<API.Account.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Account.Payload>[]> {
  return useContractQuery<API.Account.Payload>(TemplateIds.Account, filter, options);
}

/** Query Claims_Lifecycle_Rule contracts with full type safety. */
export function useRules(
  filter?: Partial<API.Claims_Lifecycle_Rule.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Claims_Lifecycle_Rule.Payload>[]> {
  return useContractQuery<API.Claims_Lifecycle_Rule.Payload>(TemplateIds.Claims_Lifecycle_Rule, filter, options);
}

/** Query Data_Numeric_Observation_Factory contracts with full type safety. */
export function useObservationFactories(
  filter?: Partial<API.Data_Numeric_Observation_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Data_Numeric_Observation_Factory.Payload>[]> {
  return useContractQuery<API.Data_Numeric_Observation_Factory.Payload>(TemplateIds.Data_Numeric_Observation_Factory, filter, options);
}

/** Query Data_Numeric_Observation contracts with full type safety. */
export function useObservations(
  filter?: Partial<API.Data_Numeric_Observation.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Data_Numeric_Observation.Payload>[]> {
  return useContractQuery<API.Data_Numeric_Observation.Payload>(TemplateIds.Data_Numeric_Observation, filter, options);
}

/** Query Data_Reference_HolidayCalendar_Factory contracts with full type safety. */
export function useHolidayCalendarFactories(
  filter?: Partial<API.Data_Reference_HolidayCalendar_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Data_Reference_HolidayCalendar_Factory.Payload>[]> {
  return useContractQuery<API.Data_Reference_HolidayCalendar_Factory.Payload>(TemplateIds.Data_Reference_HolidayCalendar_Factory, filter, options);
}

/** Query Data_Reference_HolidayCalendar contracts with full type safety. */
export function useHolidayCalendars(
  filter?: Partial<API.Data_Reference_HolidayCalendar.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Data_Reference_HolidayCalendar.Payload>[]> {
  return useContractQuery<API.Data_Reference_HolidayCalendar.Payload>(TemplateIds.Data_Reference_HolidayCalendar, filter, options);
}

/** Query Data_Time_DateClock contracts with full type safety. */
export function useDateClocks(
  filter?: Partial<API.Data_Time_DateClock.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Data_Time_DateClock.Payload>[]> {
  return useContractQuery<API.Data_Time_DateClock.Payload>(TemplateIds.Data_Time_DateClock, filter, options);
}

/** Query Data_Time_DateClockUpdate_DateClockUpdateEvent contracts with full type safety. */
export function useDateClockUpdateEvents(
  filter?: Partial<API.Data_Time_DateClockUpdate_DateClockUpdateEvent.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Data_Time_DateClockUpdate_DateClockUpdateEvent.Payload>[]> {
  return useContractQuery<API.Data_Time_DateClockUpdate_DateClockUpdateEvent.Payload>(TemplateIds.Data_Time_DateClockUpdate_DateClockUpdateEvent, filter, options);
}

/** Query Data_Time_LedgerTime contracts with full type safety. */
export function useLedgerTimes(
  filter?: Partial<API.Data_Time_LedgerTime.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Data_Time_LedgerTime.Payload>[]> {
  return useContractQuery<API.Data_Time_LedgerTime.Payload>(TemplateIds.Data_Time_LedgerTime, filter, options);
}

/** Query Holding_BaseHolding contracts with full type safety. */
export function useBaseHoldings(
  filter?: Partial<API.Holding_BaseHolding.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Holding_BaseHolding.Payload>[]> {
  return useContractQuery<API.Holding_BaseHolding.Payload>(TemplateIds.Holding_BaseHolding, filter, options);
}

/** Query Holding_Factory contracts with full type safety. */
export function useHoldingFactories(
  filter?: Partial<API.Holding_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Holding_Factory.Payload>[]> {
  return useContractQuery<API.Holding_Factory.Payload>(TemplateIds.Holding_Factory, filter, options);
}

/** Query Holding_Fungible contracts with full type safety. */
export function useFungibles(
  filter?: Partial<API.Holding_Fungible.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Holding_Fungible.Payload>[]> {
  return useContractQuery<API.Holding_Fungible.Payload>(TemplateIds.Holding_Fungible, filter, options);
}

/** Query Holding_Transferable contracts with full type safety. */
export function useTransferables(
  filter?: Partial<API.Holding_Transferable.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Holding_Transferable.Payload>[]> {
  return useContractQuery<API.Holding_Transferable.Payload>(TemplateIds.Holding_Transferable, filter, options);
}

/** Query Holding_TransferableFungible contracts with full type safety. */
export function useTransferableFungibles(
  filter?: Partial<API.Holding_TransferableFungible.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Holding_TransferableFungible.Payload>[]> {
  return useContractQuery<API.Holding_TransferableFungible.Payload>(TemplateIds.Holding_TransferableFungible, filter, options);
}

/** Query Bond_Callable_Factory contracts with full type safety. */
export function useCallableFactories(
  filter?: Partial<API.Bond_Callable_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Bond_Callable_Factory.Payload>[]> {
  return useContractQuery<API.Bond_Callable_Factory.Payload>(TemplateIds.Bond_Callable_Factory, filter, options);
}

/** Query Bond_Callable_Instrument contracts with full type safety. */
export function useInstruments(
  filter?: Partial<API.Bond_Callable_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Bond_Callable_Instrument.Payload>[]> {
  return useContractQuery<API.Bond_Callable_Instrument.Payload>(TemplateIds.Bond_Callable_Instrument, filter, options);
}

/** Query Bond_FixedRate_Factory contracts with full type safety. */
export function useFixedRateFactories(
  filter?: Partial<API.Bond_FixedRate_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Bond_FixedRate_Factory.Payload>[]> {
  return useContractQuery<API.Bond_FixedRate_Factory.Payload>(TemplateIds.Bond_FixedRate_Factory, filter, options);
}

/** Query Bond_FixedRate_Instrument contracts with full type safety. */
export function useFixedRateInstruments(
  filter?: Partial<API.Bond_FixedRate_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Bond_FixedRate_Instrument.Payload>[]> {
  return useContractQuery<API.Bond_FixedRate_Instrument.Payload>(TemplateIds.Bond_FixedRate_Instrument, filter, options);
}

/** Query Bond_FloatingRate_Factory contracts with full type safety. */
export function useFloatingRateFactories(
  filter?: Partial<API.Bond_FloatingRate_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Bond_FloatingRate_Factory.Payload>[]> {
  return useContractQuery<API.Bond_FloatingRate_Factory.Payload>(TemplateIds.Bond_FloatingRate_Factory, filter, options);
}

/** Query Bond_FloatingRate_Instrument contracts with full type safety. */
export function useFloatingRateInstruments(
  filter?: Partial<API.Bond_FloatingRate_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Bond_FloatingRate_Instrument.Payload>[]> {
  return useContractQuery<API.Bond_FloatingRate_Instrument.Payload>(TemplateIds.Bond_FloatingRate_Instrument, filter, options);
}

/** Query Bond_InflationLinked_Factory contracts with full type safety. */
export function useInflationLinkedFactories(
  filter?: Partial<API.Bond_InflationLinked_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Bond_InflationLinked_Factory.Payload>[]> {
  return useContractQuery<API.Bond_InflationLinked_Factory.Payload>(TemplateIds.Bond_InflationLinked_Factory, filter, options);
}

/** Query Bond_InflationLinked_Instrument contracts with full type safety. */
export function useInflationLinkedInstruments(
  filter?: Partial<API.Bond_InflationLinked_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Bond_InflationLinked_Instrument.Payload>[]> {
  return useContractQuery<API.Bond_InflationLinked_Instrument.Payload>(TemplateIds.Bond_InflationLinked_Instrument, filter, options);
}

/** Query Bond_ZeroCoupon_Factory contracts with full type safety. */
export function useZeroCouponFactories(
  filter?: Partial<API.Bond_ZeroCoupon_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Bond_ZeroCoupon_Factory.Payload>[]> {
  return useContractQuery<API.Bond_ZeroCoupon_Factory.Payload>(TemplateIds.Bond_ZeroCoupon_Factory, filter, options);
}

/** Query Bond_ZeroCoupon_Instrument contracts with full type safety. */
export function useZeroCouponInstruments(
  filter?: Partial<API.Bond_ZeroCoupon_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Bond_ZeroCoupon_Instrument.Payload>[]> {
  return useContractQuery<API.Bond_ZeroCoupon_Instrument.Payload>(TemplateIds.Bond_ZeroCoupon_Instrument, filter, options);
}

/** Query Equity_Factory contracts with full type safety. */
export function useEquityFactories(
  filter?: Partial<API.Equity_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Equity_Factory.Payload>[]> {
  return useContractQuery<API.Equity_Factory.Payload>(TemplateIds.Equity_Factory, filter, options);
}

/** Query Equity_Instrument contracts with full type safety. */
export function useEquityInstruments(
  filter?: Partial<API.Equity_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Equity_Instrument.Payload>[]> {
  return useContractQuery<API.Equity_Instrument.Payload>(TemplateIds.Equity_Instrument, filter, options);
}

/** Query Generic_Factory contracts with full type safety. */
export function useGenericFactories(
  filter?: Partial<API.Generic_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Generic_Factory.Payload>[]> {
  return useContractQuery<API.Generic_Factory.Payload>(TemplateIds.Generic_Factory, filter, options);
}

/** Query Generic_Instrument contracts with full type safety. */
export function useGenericInstruments(
  filter?: Partial<API.Generic_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Generic_Instrument.Payload>[]> {
  return useContractQuery<API.Generic_Instrument.Payload>(TemplateIds.Generic_Instrument, filter, options);
}

/** Query Generic_Lifecycle_Rule contracts with full type safety. */
export function useLifecycleRules(
  filter?: Partial<API.Generic_Lifecycle_Rule.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Generic_Lifecycle_Rule.Payload>[]> {
  return useContractQuery<API.Generic_Lifecycle_Rule.Payload>(TemplateIds.Generic_Lifecycle_Rule, filter, options);
}

/** Query Option_BarrierEuropeanCash_Factory contracts with full type safety. */
export function useBarrierEuropeanCashFactories(
  filter?: Partial<API.Option_BarrierEuropeanCash_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Option_BarrierEuropeanCash_Factory.Payload>[]> {
  return useContractQuery<API.Option_BarrierEuropeanCash_Factory.Payload>(TemplateIds.Option_BarrierEuropeanCash_Factory, filter, options);
}

/** Query Option_BarrierEuropeanCash_Instrument contracts with full type safety. */
export function useBarrierEuropeanCashInstruments(
  filter?: Partial<API.Option_BarrierEuropeanCash_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Option_BarrierEuropeanCash_Instrument.Payload>[]> {
  return useContractQuery<API.Option_BarrierEuropeanCash_Instrument.Payload>(TemplateIds.Option_BarrierEuropeanCash_Instrument, filter, options);
}

/** Query Option_Dividend_Election_Factory contracts with full type safety. */
export function useElectionFactories(
  filter?: Partial<API.Option_Dividend_Election_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Option_Dividend_Election_Factory.Payload>[]> {
  return useContractQuery<API.Option_Dividend_Election_Factory.Payload>(TemplateIds.Option_Dividend_Election_Factory, filter, options);
}

/** Query Option_Dividend_Factory contracts with full type safety. */
export function useDividendFactories(
  filter?: Partial<API.Option_Dividend_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Option_Dividend_Factory.Payload>[]> {
  return useContractQuery<API.Option_Dividend_Factory.Payload>(TemplateIds.Option_Dividend_Factory, filter, options);
}

/** Query Option_Dividend_Instrument contracts with full type safety. */
export function useDividendInstruments(
  filter?: Partial<API.Option_Dividend_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Option_Dividend_Instrument.Payload>[]> {
  return useContractQuery<API.Option_Dividend_Instrument.Payload>(TemplateIds.Option_Dividend_Instrument, filter, options);
}

/** Query Option_EuropeanCash_Factory contracts with full type safety. */
export function useEuropeanCashFactories(
  filter?: Partial<API.Option_EuropeanCash_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Option_EuropeanCash_Factory.Payload>[]> {
  return useContractQuery<API.Option_EuropeanCash_Factory.Payload>(TemplateIds.Option_EuropeanCash_Factory, filter, options);
}

/** Query Option_EuropeanCash_Instrument contracts with full type safety. */
export function useEuropeanCashInstruments(
  filter?: Partial<API.Option_EuropeanCash_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Option_EuropeanCash_Instrument.Payload>[]> {
  return useContractQuery<API.Option_EuropeanCash_Instrument.Payload>(TemplateIds.Option_EuropeanCash_Instrument, filter, options);
}

/** Query Option_EuropeanPhysical_Factory contracts with full type safety. */
export function useEuropeanPhysicalFactories(
  filter?: Partial<API.Option_EuropeanPhysical_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Option_EuropeanPhysical_Factory.Payload>[]> {
  return useContractQuery<API.Option_EuropeanPhysical_Factory.Payload>(TemplateIds.Option_EuropeanPhysical_Factory, filter, options);
}

/** Query Option_EuropeanPhysical_Instrument contracts with full type safety. */
export function useEuropeanPhysicalInstruments(
  filter?: Partial<API.Option_EuropeanPhysical_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Option_EuropeanPhysical_Instrument.Payload>[]> {
  return useContractQuery<API.Option_EuropeanPhysical_Instrument.Payload>(TemplateIds.Option_EuropeanPhysical_Instrument, filter, options);
}

/** Query StructuredProduct_AutoCallable_Factory contracts with full type safety. */
export function useAutoCallableFactories(
  filter?: Partial<API.StructuredProduct_AutoCallable_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.StructuredProduct_AutoCallable_Factory.Payload>[]> {
  return useContractQuery<API.StructuredProduct_AutoCallable_Factory.Payload>(TemplateIds.StructuredProduct_AutoCallable_Factory, filter, options);
}

/** Query StructuredProduct_AutoCallable_Instrument contracts with full type safety. */
export function useAutoCallableInstruments(
  filter?: Partial<API.StructuredProduct_AutoCallable_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.StructuredProduct_AutoCallable_Instrument.Payload>[]> {
  return useContractQuery<API.StructuredProduct_AutoCallable_Instrument.Payload>(TemplateIds.StructuredProduct_AutoCallable_Instrument, filter, options);
}

/** Query StructuredProduct_BarrierReverseConvertible_Factory contracts with full type safety. */
export function useBarrierReverseConvertibleFactories(
  filter?: Partial<API.StructuredProduct_BarrierReverseConvertible_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.StructuredProduct_BarrierReverseConvertible_Factory.Payload>[]> {
  return useContractQuery<API.StructuredProduct_BarrierReverseConvertible_Factory.Payload>(TemplateIds.StructuredProduct_BarrierReverseConvertible_Factory, filter, options);
}

/** Query StructuredProduct_BarrierReverseConvertible_Instrument contracts with full type safety. */
export function useBarrierReverseConvertibleInstruments(
  filter?: Partial<API.StructuredProduct_BarrierReverseConvertible_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.StructuredProduct_BarrierReverseConvertible_Instrument.Payload>[]> {
  return useContractQuery<API.StructuredProduct_BarrierReverseConvertible_Instrument.Payload>(TemplateIds.StructuredProduct_BarrierReverseConvertible_Instrument, filter, options);
}

/** Query Swap_Asset_DistributionRule contracts with full type safety. */
export function useDistributionRules(
  filter?: Partial<API.Swap_Asset_DistributionRule.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Swap_Asset_DistributionRule.Payload>[]> {
  return useContractQuery<API.Swap_Asset_DistributionRule.Payload>(TemplateIds.Swap_Asset_DistributionRule, filter, options);
}

/** Query Swap_Asset_Factory contracts with full type safety. */
export function useAssetFactories(
  filter?: Partial<API.Swap_Asset_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Swap_Asset_Factory.Payload>[]> {
  return useContractQuery<API.Swap_Asset_Factory.Payload>(TemplateIds.Swap_Asset_Factory, filter, options);
}

/** Query Swap_Asset_Instrument contracts with full type safety. */
export function useAssetInstruments(
  filter?: Partial<API.Swap_Asset_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Swap_Asset_Instrument.Payload>[]> {
  return useContractQuery<API.Swap_Asset_Instrument.Payload>(TemplateIds.Swap_Asset_Instrument, filter, options);
}

/** Query Swap_CreditDefault_Factory contracts with full type safety. */
export function useCreditDefaultFactories(
  filter?: Partial<API.Swap_CreditDefault_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Swap_CreditDefault_Factory.Payload>[]> {
  return useContractQuery<API.Swap_CreditDefault_Factory.Payload>(TemplateIds.Swap_CreditDefault_Factory, filter, options);
}

/** Query Swap_CreditDefault_Instrument contracts with full type safety. */
export function useCreditDefaultInstruments(
  filter?: Partial<API.Swap_CreditDefault_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Swap_CreditDefault_Instrument.Payload>[]> {
  return useContractQuery<API.Swap_CreditDefault_Instrument.Payload>(TemplateIds.Swap_CreditDefault_Instrument, filter, options);
}

/** Query Swap_Currency_Factory contracts with full type safety. */
export function useCurrencyFactories(
  filter?: Partial<API.Swap_Currency_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Swap_Currency_Factory.Payload>[]> {
  return useContractQuery<API.Swap_Currency_Factory.Payload>(TemplateIds.Swap_Currency_Factory, filter, options);
}

/** Query Swap_Currency_Instrument contracts with full type safety. */
export function useCurrencyInstruments(
  filter?: Partial<API.Swap_Currency_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Swap_Currency_Instrument.Payload>[]> {
  return useContractQuery<API.Swap_Currency_Instrument.Payload>(TemplateIds.Swap_Currency_Instrument, filter, options);
}

/** Query Swap_ForeignExchange_Factory contracts with full type safety. */
export function useForeignExchangeFactories(
  filter?: Partial<API.Swap_ForeignExchange_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Swap_ForeignExchange_Factory.Payload>[]> {
  return useContractQuery<API.Swap_ForeignExchange_Factory.Payload>(TemplateIds.Swap_ForeignExchange_Factory, filter, options);
}

/** Query Swap_ForeignExchange_Instrument contracts with full type safety. */
export function useForeignExchangeInstruments(
  filter?: Partial<API.Swap_ForeignExchange_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Swap_ForeignExchange_Instrument.Payload>[]> {
  return useContractQuery<API.Swap_ForeignExchange_Instrument.Payload>(TemplateIds.Swap_ForeignExchange_Instrument, filter, options);
}

/** Query Swap_Fpml_Factory contracts with full type safety. */
export function useFpmlFactories(
  filter?: Partial<API.Swap_Fpml_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Swap_Fpml_Factory.Payload>[]> {
  return useContractQuery<API.Swap_Fpml_Factory.Payload>(TemplateIds.Swap_Fpml_Factory, filter, options);
}

/** Query Swap_Fpml_Instrument contracts with full type safety. */
export function useFpmlInstruments(
  filter?: Partial<API.Swap_Fpml_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Swap_Fpml_Instrument.Payload>[]> {
  return useContractQuery<API.Swap_Fpml_Instrument.Payload>(TemplateIds.Swap_Fpml_Instrument, filter, options);
}

/** Query Swap_InterestRate_Factory contracts with full type safety. */
export function useInterestRateFactories(
  filter?: Partial<API.Swap_InterestRate_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Swap_InterestRate_Factory.Payload>[]> {
  return useContractQuery<API.Swap_InterestRate_Factory.Payload>(TemplateIds.Swap_InterestRate_Factory, filter, options);
}

/** Query Swap_InterestRate_Instrument contracts with full type safety. */
export function useInterestRateInstruments(
  filter?: Partial<API.Swap_InterestRate_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Swap_InterestRate_Instrument.Payload>[]> {
  return useContractQuery<API.Swap_InterestRate_Instrument.Payload>(TemplateIds.Swap_InterestRate_Instrument, filter, options);
}

/** Query Token_Factory contracts with full type safety. */
export function useTokenFactories(
  filter?: Partial<API.Token_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Token_Factory.Payload>[]> {
  return useContractQuery<API.Token_Factory.Payload>(TemplateIds.Token_Factory, filter, options);
}

/** Query Token_Instrument contracts with full type safety. */
export function useTokenInstruments(
  filter?: Partial<API.Token_Instrument.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Token_Instrument.Payload>[]> {
  return useContractQuery<API.Token_Instrument.Payload>(TemplateIds.Token_Instrument, filter, options);
}

/** Query Account_Account_Reference contracts with full type safety. */
export function useReferences(
  filter?: Partial<API.Account_Account_Reference.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Account_Account_Reference.Payload>[]> {
  return useContractQuery<API.Account_Account_Reference.Payload>(TemplateIds.Account_Account_Reference, filter, options);
}

/** Query Holding_Factory_Reference contracts with full type safety. */
export function useFactoryReferences(
  filter?: Partial<API.Holding_Factory_Reference.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Holding_Factory_Reference.Payload>[]> {
  return useContractQuery<API.Holding_Factory_Reference.Payload>(TemplateIds.Holding_Factory_Reference, filter, options);
}

/** Query Base_Instrument_Reference contracts with full type safety. */
export function useInstrumentReferences(
  filter?: Partial<API.Base_Instrument_Reference.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Base_Instrument_Reference.Payload>[]> {
  return useContractQuery<API.Base_Instrument_Reference.Payload>(TemplateIds.Base_Instrument_Reference, filter, options);
}

/** Query Lifecycle_Effect contracts with full type safety. */
export function useEffects(
  filter?: Partial<API.Lifecycle_Effect.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Lifecycle_Effect.Payload>[]> {
  return useContractQuery<API.Lifecycle_Effect.Payload>(TemplateIds.Lifecycle_Effect, filter, options);
}

/** Query Lifecycle_Election_Factory contracts with full type safety. */
export function useLifecycleElectionFactories(
  filter?: Partial<API.Lifecycle_Election_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Lifecycle_Election_Factory.Payload>[]> {
  return useContractQuery<API.Lifecycle_Election_Factory.Payload>(TemplateIds.Lifecycle_Election_Factory, filter, options);
}

/** Query Lifecycle_Election contracts with full type safety. */
export function useElections(
  filter?: Partial<API.Lifecycle_Election.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Lifecycle_Election.Payload>[]> {
  return useContractQuery<API.Lifecycle_Election.Payload>(TemplateIds.Lifecycle_Election, filter, options);
}

/** Query Lifecycle_ElectionEffect contracts with full type safety. */
export function useElectionEffects(
  filter?: Partial<API.Lifecycle_ElectionEffect.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Lifecycle_ElectionEffect.Payload>[]> {
  return useContractQuery<API.Lifecycle_ElectionEffect.Payload>(TemplateIds.Lifecycle_ElectionEffect, filter, options);
}

/** Query Lifecycle_Distribution_Event contracts with full type safety. */
export function useEvents(
  filter?: Partial<API.Lifecycle_Distribution_Event.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Lifecycle_Distribution_Event.Payload>[]> {
  return useContractQuery<API.Lifecycle_Distribution_Event.Payload>(TemplateIds.Lifecycle_Distribution_Event, filter, options);
}

/** Query Lifecycle_Replacement_Event contracts with full type safety. */
export function useReplacementEvents(
  filter?: Partial<API.Lifecycle_Replacement_Event.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Lifecycle_Replacement_Event.Payload>[]> {
  return useContractQuery<API.Lifecycle_Replacement_Event.Payload>(TemplateIds.Lifecycle_Replacement_Event, filter, options);
}

/** Query Lifecycle_Claim_Rule contracts with full type safety. */
export function useClaimRules(
  filter?: Partial<API.Lifecycle_Claim_Rule.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Lifecycle_Claim_Rule.Payload>[]> {
  return useContractQuery<API.Lifecycle_Claim_Rule.Payload>(TemplateIds.Lifecycle_Claim_Rule, filter, options);
}

/** Query Lifecycle_Distribution_Rule contracts with full type safety. */
export function useLifecycleDistributionRules(
  filter?: Partial<API.Lifecycle_Distribution_Rule.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Lifecycle_Distribution_Rule.Payload>[]> {
  return useContractQuery<API.Lifecycle_Distribution_Rule.Payload>(TemplateIds.Lifecycle_Distribution_Rule, filter, options);
}

/** Query Lifecycle_Replacement_Rule contracts with full type safety. */
export function useReplacementRules(
  filter?: Partial<API.Lifecycle_Replacement_Rule.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Lifecycle_Replacement_Rule.Payload>[]> {
  return useContractQuery<API.Lifecycle_Replacement_Rule.Payload>(TemplateIds.Lifecycle_Replacement_Rule, filter, options);
}

/** Query Settlement_Batch contracts with full type safety. */
export function useBatches(
  filter?: Partial<API.Settlement_Batch.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Settlement_Batch.Payload>[]> {
  return useContractQuery<API.Settlement_Batch.Payload>(TemplateIds.Settlement_Batch, filter, options);
}

/** Query Settlement_Factory contracts with full type safety. */
export function useSettlementFactories(
  filter?: Partial<API.Settlement_Factory.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Settlement_Factory.Payload>[]> {
  return useContractQuery<API.Settlement_Factory.Payload>(TemplateIds.Settlement_Factory, filter, options);
}

/** Query Settlement_Instruction contracts with full type safety. */
export function useInstructions(
  filter?: Partial<API.Settlement_Instruction.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Settlement_Instruction.Payload>[]> {
  return useContractQuery<API.Settlement_Instruction.Payload>(TemplateIds.Settlement_Instruction, filter, options);
}

/** Query Settlement_RouteProvider_IntermediatedStatic contracts with full type safety. */
export function useIntermediatedStatics(
  filter?: Partial<API.Settlement_RouteProvider_IntermediatedStatic.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Settlement_RouteProvider_IntermediatedStatic.Payload>[]> {
  return useContractQuery<API.Settlement_RouteProvider_IntermediatedStatic.Payload>(TemplateIds.Settlement_RouteProvider_IntermediatedStatic, filter, options);
}

/** Query Settlement_RouteProvider_SingleCustodian contracts with full type safety. */
export function useSingleCustodians(
  filter?: Partial<API.Settlement_RouteProvider_SingleCustodian.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Settlement_RouteProvider_SingleCustodian.Payload>[]> {
  return useContractQuery<API.Settlement_RouteProvider_SingleCustodian.Payload>(TemplateIds.Settlement_RouteProvider_SingleCustodian, filter, options);
}

/** Query LunarDollar contracts with full type safety. */
export function useLunarDollars(
  filter?: Partial<API.LunarDollar.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.LunarDollar.Payload>[]> {
  return useContractQuery<API.LunarDollar.Payload>(TemplateIds.LunarDollar, filter, options);
}

/** Query PaymentReceiver contracts with full type safety. */
export function usePaymentReceivers(
  filter?: Partial<API.PaymentReceiver.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.PaymentReceiver.Payload>[]> {
  return useContractQuery<API.PaymentReceiver.Payload>(TemplateIds.PaymentReceiver, filter, options);
}

/** Query PaymentReceiver_AccessGrant contracts with full type safety. */
export function useAccessGrants(
  filter?: Partial<API.PaymentReceiver_AccessGrant.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.PaymentReceiver_AccessGrant.Payload>[]> {
  return useContractQuery<API.PaymentReceiver_AccessGrant.Payload>(TemplateIds.PaymentReceiver_AccessGrant, filter, options);
}

/** Query TransferRequest contracts with full type safety. */
export function useTransferRequests(
  filter?: Partial<API.TransferRequest.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.TransferRequest.Payload>[]> {
  return useContractQuery<API.TransferRequest.Payload>(TemplateIds.TransferRequest, filter, options);
}

/** Query Workflow_CreateAccount_Request contracts with full type safety. */
export function useRequests(
  filter?: Partial<API.Workflow_CreateAccount_Request.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Workflow_CreateAccount_Request.Payload>[]> {
  return useContractQuery<API.Workflow_CreateAccount_Request.Payload>(TemplateIds.Workflow_CreateAccount_Request, filter, options);
}

/** Query Workflow_CreditAccount_Request contracts with full type safety. */
export function useCreditAccountRequests(
  filter?: Partial<API.Workflow_CreditAccount_Request.Payload>,
  options?: { enabled?: boolean }
): UseQueryResult<Contract<API.Workflow_CreditAccount_Request.Payload>[]> {
  return useContractQuery<API.Workflow_CreditAccount_Request.Payload>(TemplateIds.Workflow_CreditAccount_Request, filter, options);
}

