// ledger/streaming.ts
// SSE streaming client for Canton JSON API
// DO NOT EDIT - Generated by generate-canton-api.ts

export interface ContractEvent {
  type: 'created' | 'archived';
  contractId: string;
  templateId: string;
  payload?: unknown;
  offset?: string;
}

export interface StreamOptions {
  templateIds: string[];
  filter?: Record<string, unknown>;
  onContract: (event: ContractEvent) => void;
  onError?: (error: Error) => void;
  onEnd?: () => void;
}

export class LedgerStream {
  private eventSource: EventSource | null = null;
  private _isConnected = false;

  get isConnected(): boolean {
    return this._isConnected;
  }

  connect(baseUrl: string, token: string | undefined, _party: string, options: StreamOptions): void {
    if (this.eventSource) {
      this.disconnect();
    }

    const params = new URLSearchParams({
      templateIds: options.templateIds.join(','),
    });
    if (options.filter) {
      params.set('query', JSON.stringify(options.filter));
    }

    const url = `${baseUrl}/v1/stream/query?${params.toString()}`;

    this.eventSource = new EventSource(url, {
      withCredentials: !!token,
    });

    this.eventSource.onopen = () => {
      this._isConnected = true;
    };

    this.eventSource.onmessage = (event) => {
      try {
        const data = JSON.parse(event.data);
        if (data.events) {
          for (const e of data.events) {
            if (e.created) {
              options.onContract({
                type: 'created',
                contractId: e.created.contractId,
                templateId: e.created.templateId,
                payload: e.created.payload,
                offset: data.offset,
              });
            } else if (e.archived) {
              options.onContract({
                type: 'archived',
                contractId: e.archived.contractId,
                templateId: e.archived.templateId,
                offset: data.offset,
              });
            }
          }
        }
      } catch (err) {
        options.onError?.(err instanceof Error ? err : new Error(String(err)));
      }
    };

    this.eventSource.onerror = (_err) => {
      this._isConnected = false;
      options.onError?.(new Error('Stream connection error'));
    };
  }

  disconnect(): void {
    if (this.eventSource) {
      this.eventSource.close();
      this.eventSource = null;
      this._isConnected = false;
    }
  }
}

export function createContractStream(): LedgerStream {
  return new LedgerStream();
}
