// utils/damlMap.ts
// Helpers for working with DamlMap<K, V> (array-of-pairs)
// DO NOT EDIT - Generated by generate-canton-api.ts

import type { DamlMap } from '../core/primitives';

/**
 * Convert a Record<string, V> to a DamlMap<string, V>.
 * NOTE: Duplicates are not possible in a Record.
 */
export function damlMapFromRecord<V>(record: Record<string, V>): DamlMap<string, V> {
  return Object.entries(record) as DamlMap<string, V>;
}

/**
 * Convert a DamlMap<string, V> to a Record<string, V>.
 * NOTE: If the DamlMap contains duplicate keys, the last value wins.
 */
export function damlMapToRecord<V>(map: DamlMap<string, V>): Record<string, V> {
  return Object.fromEntries(map) as Record<string, V>;
}

/** Get a value from a DamlMap using strict equality on keys. */
export function damlMapGet<K, V>(map: DamlMap<K, V>, key: K): V | undefined {
  for (const [k, v] of map) {
    if (k === key) return v;
  }
  return undefined;
}

/** Set a value in a DamlMap (returns a new map). */
export function damlMapSet<K, V>(map: DamlMap<K, V>, key: K, value: V): DamlMap<K, V> {
  const out: Array<[K, V]> = [];
  let replaced = false;
  for (const [k, v] of map) {
    if (k === key) {
      out.push([key, value]);
      replaced = true;
    } else {
      out.push([k, v]);
    }
  }
  if (!replaced) out.push([key, value]);
  return out as DamlMap<K, V>;
}

/** Delete a key from a DamlMap (returns a new map). */
export function damlMapDelete<K, V>(map: DamlMap<K, V>, key: K): DamlMap<K, V> {
  return map.filter(([k]) => k !== key) as DamlMap<K, V>;
}
