// utils/datetime.ts
// Date and time utilities for Canton
// DO NOT EDIT - Generated by generate-canton-api.ts

import type { Time } from '../core/primitives';

export function toCantonTime(date: Date): Time {
  return date.toISOString();
}

export function fromCantonTime(time: Time): Date {
  return new Date(time);
}

export function formatDate(time: Time, options?: Intl.DateTimeFormatOptions): string {
  const date = fromCantonTime(time);
  return date.toLocaleDateString(undefined, options);
}

export function formatDateTime(time: Time): string {
  const date = fromCantonTime(time);
  return date.toLocaleString();
}

export function nowAsCantonTime(): Time {
  return toCantonTime(new Date());
}
