// utils/ids.ts
// ID and key creation utilities
// DO NOT EDIT - Generated by generate-canton-api.ts

import type { Party } from "../core/primitives";
import type {
  Id,
  AccountKey,
  InstrumentKey,
  HoldingFactoryKey,
} from "../core/interfaces";

export function createId(value: string): Id {
  return { unpack: value };
}

export function createAccountKey(
  custodian: Party,
  owner: Party,
  id: string
): AccountKey {
  return { custodian, owner, id: createId(id) };
}

export function createInstrumentKey(
  depository: Party,
  issuer: Party,
  id: string,
  version: string = "1"
): InstrumentKey {
  return {
    depository,
    issuer,
    id: createId(id),
    version,
    holdingStandard: "TransferableFungible",
  };
}

export function createHoldingFactoryKey(
  provider: Party,
  id: string
): HoldingFactoryKey {
  return { provider, id: createId(id) };
}

export function idToString(id: Id): string {
  return id.unpack;
}

export function generateUniqueId(prefix: string = "id"): string {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}
