// utils/amounts.ts
// Amount utilities for financial calculations
// DO NOT EDIT - Generated by generate-canton-api.ts

import type { Numeric } from '../core/primitives';

export function normalizeAmount(value: string | number): Numeric {
  if (typeof value === 'number') {
    return value.toString();
  }
  return value.replace(/,/g, '');
}

export function formatAmount(value: Numeric, decimals: number = 2): string {
  const num = parseFloat(value);
  return num.toLocaleString(undefined, {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  });
}

export function addAmounts(a: Numeric, b: Numeric): Numeric {
  const numA = parseFloat(a);
  const numB = parseFloat(b);
  return (numA + numB).toString();
}

export function subtractAmounts(a: Numeric, b: Numeric): Numeric {
  const numA = parseFloat(a);
  const numB = parseFloat(b);
  return (numA - numB).toString();
}

export function isValidAmount(value: string): boolean {
  const num = parseFloat(value);
  return !isNaN(num) && isFinite(num);
}

export function compareAmounts(a: Numeric, b: Numeric): number {
  const numA = parseFloat(a);
  const numB = parseFloat(b);
  return numA - numB;
}
